import {
  SiJavascript, SiTypescript, SiPython, SiCplusplus, SiSolidity,
  SiReact, SiNextdotjs, SiHtml5, SiCss3, SiTailwindcss, SiChakraui,
  SiNodedotjs, SiExpress, SiMongodb, SiMysql, SiPostgresql, SiFirebase,
  SiTensorflow, SiKeras, SiScikitlearn, SiOpencv, SiPytorch, SiOpenai,
  SiGit, SiDocker, SiKubernetes, SiGooglecloud, SiSupabase, SiPrisma,
  SiJenkins, SiGithubcopilot, SiNestjs, SiGraphql, SiApollographql,
  SiSocketdotio, SiRedux, SiReactquery, SiFramer, SiVite, SiStorybook,
  SiReacthookform, SiHuggingface, SiGithubactions, SiVercel, SiNetlify,
  SiTerraform, SiCloudflare, SiRedis, SiNginx, SiApachekafka, SiSqlite,
  SiJest, SiCypress, SiTestinglibrary, SiAndroidstudio, SiEclipseide,
  SiApache, SiJupyter, SiGooglecolab, SiIntellijidea, SiPycharm,
  SiWebstorm, SiSublimetext, SiFastapi, SiApachespark, SiSnowflake,
  SiPandas, SiNumpy, SiDbt, SiPlotly, SiApacheairflow, SiMlflow, SiLangchain,
  SiDjango,
} from "react-icons/si";
import { MdOutlineHttp, MdDevices } from "react-icons/md";
import { GiTeamIdea, GiTestTubes } from "react-icons/gi";
import { TbBrandCSharp } from "react-icons/tb";
import { VscAzure, VscCode, VscVscode } from "react-icons/vsc";
import { FaJava, FaSpaceShuttle } from "react-icons/fa";
import { HiLightningBolt, HiSparkles, HiChip, HiDatabase, HiChartBar } from "react-icons/hi";

// Images
import CRMThumbnail from "@/app/assets/CRM Thumbnail.png";
import HRMThumbnail from "@/app/assets/HRM Thumbnail.png";
import AIDBThumbnail from "@/app/assets/AIDashboard.png";
import EaseWebThumbnail from "@/app/assets/EaseWen Thumbnail.png";
import StartupNinjaImg from "@/app/assets/startup_ninja.png";
import EsanadCRMImg from "@/app/assets/esanad_crm.png";
import GPAnalytixImg from "@/app/assets/gpanalytix.png";
import MSThesisNLPImg from "@/app/assets/ms_thesis_nlp.png";
import NexusRAGImg from "@/app/assets/nexus_rag.png";
import DevPulseImg from "@/app/assets/devpulse.png";
import PayFlowImg from "@/app/assets/payflow_gateway.png";
import TaskPulseImg from "@/app/assets/taskpulse.png";
import HRMMartechsolImg from "@/app/assets/hrm_martechsol.png";
import RMGLMSImg from "@/app/assets/rmg_lms.png";
import OctaVoiceImg from "@/app/assets/octa_voice.png";
import CloudDeskImg from "@/app/assets/clouddesk.png";
import MediCareImg from "@/app/assets/medicare.png";

// New project images (AI-generated)
import AgentFlowImg from "@/app/assets/agentflow_llm.png";
import StreamPulseImg from "@/app/assets/streampulse_pipeline.png";
import DataVaultImg from "@/app/assets/datavault_warehouse.png";
import FeatureForgeImg from "@/app/assets/featureforge_ml.png";
import ModelServeImg from "@/app/assets/modelserve_hub.png";
import AutoTrainImg from "@/app/assets/autotrain_mlops.png";
import ChurnShieldImg from "@/app/assets/churnshield_analytics.png";
import FinSightImg from "@/app/assets/finsight_forecaster.png";
import DataLensImg from "@/app/assets/datalens_dashboard.png";
import LoopHireImg from "@/app/assets/loop_hire.png";
import USAResumeWritersImg from "@/app/assets/usa_resume_writers.png";
import OrionsTechImg from "@/app/assets/orions_technology.png";
import CustomLogoValleyImg from "@/app/assets/custom_logo_valley.png";


// Company Logos
import AGELogo from "@/app/assets/company_logos/age_logo.png";
import EsanadLogo from "@/app/assets/company_logos/esanad_logo.png";
import MartechsolLogo from "@/app/assets/company_logos/martechsol_logo.png";
import CharcentricLogo from "@/app/assets/company_logos/charcentric_logo.png";

export const projects = [
    {
    id: "gpanalytix",
    title: "GPAnalytix / Smart Analytics",
    subtitle: "Hospital Financial Analytics Platform",
    description: "Enterprise analytics dashboard for 200+ hospitals and APCO Worldwide; engineered ETL pipelines converting unstructured documents into KPIs.",
    longDescription: "Financial analytics platform servicing over 200 hospitals and APCO Worldwide (via SnowHeap & CharCentric). Engineered robust ETL data pipelines and document-ingestion workflows that convert unstructured financial documents into structured KPIs, surfaced through high-performance React visualization dashboards.",
    image: GPAnalytixImg,
    link: "#",
    duration: "Jan 2024 - Aug 2024",
    role: "Full-Stack Software Engineer",
    team: "6+ Members",
    client: "APCO Worldwide / Hospital Network",
    associatedWith: "Freelance",
    technologies: ["React", "Node.js", "TypeScript", "MongoDB", "ETL Pipelines", "Recharts", "Tailwind CSS"],
    features: ["Financial Document Ingestion & KPI Extraction", "Interactive Real-Time Analytics Dashboards", "Multi-Hospital Performance Metrics Sync", "Sub-Second Data Visualization Rendering"],
    challenges: ["Parsing heterogeneous financial PDF/CSV documents", "Rendering large multi-hospital datasets performantly", "Strict data privacy & encryption compliance"],
    achievements: ["Cut manual financial reporting effort by 40%", "Engineered reliable multi-source ETL pipelines", "Delivered enterprise-grade reporting for APCO Worldwide"],
    tags: ["Analytics", "ETL", "React", "Enterprise"],
  },,
    {
    id: "startup-ninja",
    title: "Startup Ninja",
    subtitle: "AI-Powered B2B SaaS Ecosystem",
    description: "Multi-tenant B2B SaaS platform with 8+ microservices, CRM lead management, document generator, GrapesJS no-code builder, and AI pipelines.",
    longDescription: "Startup Ninja is a robust, AI-driven multi-tenant B2B SaaS platform designed on an 8+ service microservices backend. It features a CRM lead-management module, an automated document generator, an AI Chat & Image Generator, and a Social Media Studio with OAuth 2.0 scheduling across platforms. Includes a GrapesJS drag-and-drop website builder, Stripe billing sync, BullMQ background queues, and Docker containerization.",
    image: StartupNinjaImg,
    link: "https://startupninja.netlify.app/",
    duration: "Sep 2024 - Present",
    role: "Senior Full-Stack Engineer",
    team: "Lead Developer",
    client: "Alvi Global Enterprises (AGE)",
    associatedWith: "Alvi Global Enterprises",
    technologies: ["MERN Stack", "TypeScript", "Microservices", "Docker", "Redis", "BullMQ", "Stripe", "OpenAI API"],
    features: ["Multi-Tenant B2B SaaS Microservices", "CRM Lead-Management & Document Generator", "GrapesJS No-Code Drag-and-Drop Builder", "Social Media Scheduling (OAuth 2.0)", "Stripe Billing & BullMQ Queue Processing"],
    challenges: ["Orchestrating 8+ microservices with sub-100ms latency", "Securing APIs with JWT rotation and token blacklisting", "Complex state management for GrapesJS editor"],
    achievements: ["Unified 4 core enterprise modules into one SaaS", "Reduced background job processing time using BullMQ", "Sub-second page rendering and high availability"],
    tags: ["SaaS", "Microservices", "MERN", "AI & Automation"],
  },,
    {
    id: "orions-technology",
    title: "Orions Technology",
    subtitle: "Modern Tech Consultancy & Software Landing Page",
    description: "High-performance agency landing page built with Next.js 15, TypeScript, and Tailwind CSS, featuring modern UI animations and interactive tech showcases.",
    longDescription: "Engineered a sleek, responsive agency landing page for Orions Technology. Built with Next.js 15, TypeScript, Tailwind CSS, and Framer Motion. Features interactive 3D tech graphic showcases, service offerings, client portfolio grids, and optimized lead-capture forms, delivering sub-second page loads and a 95+ Web Vitals score.",
    image: OrionsTechImg,
    link: "https://www.orionstechnology.com/",
    duration: "2025 - Live",
    role: "Frontend / Full-Stack Engineer",
    team: "Lead Developer",
    client: "Alvi Global Enterprises (AGE)",
    associatedWith: "Alvi Global Enterprises",
    technologies: ["Next.js 15", "TypeScript", "Tailwind CSS", "React", "Framer Motion"],
    features: ["Interactive 3D Tech Graphic Showcase", "High-Performance Next.js 15 SSR Architecture", "Responsive Lead Generation & Contact Forms", "Fluid Micro-Animations with Framer Motion"],
    challenges: ["Optimizing heavy graphic assets for mobile performance", "Cross-browser CSS backdrop-blur compatibility", "SEO meta tag structure for tech agency ranking"],
    achievements: ["95+ Google PageSpeed score", "Boosted inbound client inquiry rate", "Seamless responsive design across all viewports"],
    tags: ["Web", "Next.js", "Branding", "Marketing"],
  },,
    {
    id: "custom-logo-valley",
    title: "Custom Logo Valley",
    subtitle: "Animated Brand & Logo Design Agency Portal",
    description: "Interactive, animated brand showcase portal for custom logo design services featuring dynamic logo morphing previews and pricing tiers.",
    longDescription: "Designed and developed a vibrant, animated brand portal for Custom Logo Valley. Features an interactive vector logo morphing preview engine, dynamic logo portfolio showcase grid, transparent pricing tier selectors, and automated client consultation booking workflows built with React, TypeScript, and Framer Motion.",
    image: CustomLogoValleyImg,
    link: "https://customlogovalley.com/",
    duration: "2025 - Live",
    role: "Frontend / Full-Stack Engineer",
    team: "Lead Developer",
    client: "Alvi Global Enterprises (AGE)",
    associatedWith: "Alvi Global Enterprises",
    technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS", "Framer Motion"],
    features: ["Interactive Animated Vector Logo Morphing Preview", "Dynamic Portfolio Showcase Grid with Filtering", "Tiered Pricing Selector & Consultation Booking", "Responsive Dark Purple & Neon Aesthetic"],
    challenges: ["Handling complex vector logo morphing animations smoothly", "Maintaining high FPS performance on low-end mobile devices", "Streamlined checkout and inquiry UX"],
    achievements: ["Delivered interactive brand showcase for design agency", "Sub-second animation transitions with zero lag", "Increased customer consultation conversion"],
    tags: ["Web", "React", "Branding", "Marketing"],
  },,
    {
    id: "esanad-crm",
    title: "eSanad CRM & Website",
    subtitle: "Enterprise Insurance CRM & Portal",
    description: "Insurance CRM & corporate site with organization/employee management, insurer API sync (Adamjee, Watania), and Tap Payments policy automation.",
    longDescription: "Delivered core features for the eSanad insurance CRM and public corporate site. Developed organization and employee management modules alongside motor and travel insurance issuance tools. Integrated third-party insurer APIs (Adamjee, Watania, Insurance House) and securely integrated the Tap Payments gateway, automating policy generation upon payment validation.",
    image: EsanadCRMImg,
    link: "https://admin.esanad.com/",
    duration: "Apr 2025 - Sep 2025",
    role: "Full-Stack Software Engineer",
    team: "Contract Engineer",
    client: "eSanad UAE",
    associatedWith: "eSanad",
    technologies: ["React", "Next.js", "Node.js", "Express", "MongoDB", "Tap Payments", "Third-Party Insurance APIs"],
    features: ["Organization & Employee Insurance Modules", "Motor & Travel Insurance Policy Issuance", "Third-Party Insurer API Sync (Adamjee, Watania)", "Tap Payments Gateway Integration & Auto Issuance"],
    challenges: ["Harmonizing schema across disparate insurer APIs", "Ensuring PCI-compliant payment status validation", "Optimizing heavy MongoDB aggregation queries"],
    achievements: ["Reduced manual policy processing time by >50%", "Substantially improved MongoDB query response times", "Zero-downtime payment & policy workflow sync"],
    tags: ["Insurance", "Fintech", "CRM", "Next.js"],
  },,
    {
    id: "hrm-martechsol",
    title: "Enterprise HRM & CRM Portal",
    subtitle: "Human Resource & Operations System",
    description: "Full-featured HR system covering Attendance, Payroll, Finance, RBAC, and Ticketing, plus an integrated CRM optimizing internal operations.",
    longDescription: "Built a full-featured HRM system and integrated CRM from scratch on the MERN stack for MartechSol. Modules cover Biometric Attendance tracking, Payroll processing, Finance, Leave management, Ticketing, and granular Role-Based Access Control (RBAC). Front-end engineered with React, Redux, TypeScript, and Tailwind CSS; deployed via automated CI/CD pipelines.",
    image: HRMMartechsolImg,
    link: "https://portal.martechsol.com/",
    duration: "Oct 2024 - Apr 2025",
    role: "Full-Stack Software Engineer",
    team: "Lead Engineer",
    client: "MartechSol",
    associatedWith: "MartechSol",
    technologies: ["MERN Stack", "React", "Redux", "TypeScript", "Tailwind CSS", "Node.js", "RBAC", "CI/CD"],
    features: ["Biometric Attendance & Automated Payroll", "Finance, Leave Approvals & Helpdesk Ticketing", "Granular Role-Based Access Control (RBAC)", "Integrated Internal Sales Operations CRM"],
    challenges: ["Complex payroll deduction & tax calculations", "Enforcing strict multi-role permission matrices", "Zero-downtime CI/CD deployment pipelines"],
    achievements: ["Automated over 90% of manual HR & payroll tasks", "Reduced deployment times via automated CI/CD", "Zero payroll calculation errors across departments"],
    tags: ["HRM", "CRM", "MERN", "Enterprise"],
  },,
    {
    id: "rmg-lms",
    title: "RMG LMS Platform",
    subtitle: "Enterprise Learning Management System",
    description: "Enterprise LMS featuring a complex quizzing engine, AWS S3 media streaming, and automated certification issuance.",
    longDescription: "Contributed to the development of RMG LMS platform. Engineered an advanced quizzing engine supporting multiple question formats, automated certificate generation upon course completion, and integrated AWS S3 for secure, low-latency video and document streaming.",
    image: RMGLMSImg,
    link: "#",
    duration: "Aug 2023 - Aug 2024",
    role: "Full-Stack Software Engineer",
    team: "3+ Members",
    client: "CharCentric",
    associatedWith: "CharCentric",
    technologies: ["React", "Node.js", "TypeScript", "MongoDB", "AWS S3", "PDF Kit"],
    features: ["Complex Interactive Quizzing System", "AWS S3 Secure Media Streaming", "Automated PDF Certificate Generation", "Real-Time Course Progress Tracking"],
    challenges: ["Preventing unauthorized media downloads from S3", "Complex scoring logic and state persistence", "Responsive quiz layout across mobile screens"],
    achievements: ["Improved course-completion tracking efficiency", "Automated certificate generation & validation", "High-speed video asset delivery via S3"],
    tags: ["EdTech", "LMS", "AWS", "MERN"],
  },,
    {
    id: "ms-thesis-ai",
    title: "MS Thesis – AI Legal NLP",
    subtitle: "Pakistani Supreme Court Judgment AI Translation & Summarization",
    description: "Fine-tuned transformer models (NLLB-200, mBART-50, mT5) to translate & summarize legal judgments into Urdu and Sindhi. Poster credit at IEEE HTC 2026.",
    longDescription: "Author of a 54-page Master's thesis at MAJU supervised by Dr. Shaukat Wasi. Fine-tuned state-of-the-art transformer models (NLLB-200-distilled-600M, mBART-50, mT5) on legal datasets to automatically translate and summarize Pakistani Supreme Court judgments into Urdu and Sindhi. Implemented lexically constrained beam search, achieving an 88.9% Term Success Rate (TSR) for Urdu and 84.7% for Sindhi. Presented as a poster credit at IEEE HTC 2026.",
    image: MSThesisNLPImg,
    link: "#",
    duration: "Sep 2024 - Jul 2026",
    role: "AI / NLP Research Author",
    team: "Individual Research",
    client: "MAJU / IEEE HTC 2026",
    associatedWith: "MAJU",
    technologies: ["Python", "PyTorch", "Hugging Face", "NLLB-200", "mBART-50", "mT5", "Constrained Decoding"],
    features: ["Pakistani Supreme Court Judgment Corpus Curation", "Fine-Tuned NLLB-200, mBART-50, and mT5 Models", "Lexically Constrained Beam Search Decoding", "88.9% Urdu TSR & 84.7% Sindhi TSR Metrics"],
    challenges: ["Handling complex Pakistani legal terminology", "Fine-tuning large 600M+ parameter models on GPU resources", "Custom constrained decoding for legal accuracy"],
    achievements: ["IEEE HTC 2026 International Poster Presentation Credit", "First fine-tuned legal NLP model for Urdu & Sindhi", "54-page Master's Thesis & CGPA 3.97 / 4.00"],
    tags: ["AI", "NLP", "PyTorch", "Research"],
  },,
    {
    id: "agentflow-llm",
    title: "AgentFlow Multi-Agent LLM",
    subtitle: "Autonomous Multi-Agent Workflow Orchestration System",
    description: "LangGraph-powered multi-agent framework that autonomously decomposes complex tasks, routes them to specialized sub-agents, and synthesizes structured outputs.",
    longDescription: "AgentFlow is an enterprise-grade multi-agent orchestration system built with LangGraph and LangChain. It supports planner, researcher, coder, and critic agents that collaborate autonomously to solve complex tasks. Features persistent memory via Redis, tool use (web search, code execution, file I/O), and a FastAPI streaming backend delivering real-time token-by-token agent output to a React UI.",
    image: AgentFlowImg,
    link: "#",
    duration: "2025 - Project",
    role: "AI Engineer",
    team: "Individual Project",
    client: "AI Automation Platform",
    associatedWith: "Personal Project",
    technologies: ["Python", "LangChain", "LangGraph", "OpenAI API", "FastAPI", "Redis", "PostgreSQL"],
    features: ["Multi-Agent Task Decomposition & Routing", "Planner → Researcher → Coder → Critic Pipeline", "Real-Time Streaming Token Output via FastAPI", "Persistent Agent Memory with Redis & PostgreSQL"],
    challenges: ["Managing cyclic agent graphs without infinite loops", "Reliable tool-use across non-deterministic LLM outputs", "Streaming intermediate agent steps to the browser"],
    achievements: ["Reduced complex research task completion time by 70%", "Robust inter-agent handoff with zero data loss", "Extensible plugin system for new agent tools"],
    tags: ["AI Engineering", "LLM", "Multi-Agent", "LangChain"],
  },,
    {
    id: "nexus-rag",
    title: "Nexus RAG Engine",
    subtitle: "Enterprise Document QA & Semantic Vector Search",
    description: "Production RAG pipeline for processing multi-page PDFs, legal contracts, and manuals using pgvector hybrid search and re-ranking.",
    longDescription: "Enterprise Retrieval-Augmented Generation (RAG) system built to ingest, chunk, and index unstructured documents into a vector database. Leverages pgvector hybrid vector-keyword search, OpenAI embeddings, and re-ranking for instant, cited document Q&A.",
    image: NexusRAGImg,
    link: "#",
    duration: "2025 - Open Source",
    role: "AI Systems Engineer",
    team: "Personal Project",
    client: "Enterprise RAG Tool",
    associatedWith: "Personal Project",
    technologies: ["Next.js 15", "FastAPI", "LangChain", "pgvector", "PostgreSQL", "OpenAI Embeddings", "Tailwind CSS"],
    features: ["PDF & DocX Automatic Vector Ingestion", "Hybrid Vector & Keyword Search (pgvector)", "Source Citation & Page Number Highlighting", "FastAPI Async Processing Backend"],
    challenges: ["Optimizing chunking strategies for multi-page tables", "Minimizing LLM hallucination with strict context bounds", "Sub-200ms vector retrieval speed"],
    achievements: ["Achieved 94% retrieval accuracy on technical docs", "Sub-200ms vector search latency", "Open-source production template"],
    tags: ["AI", "RAG", "pgvector", "FastAPI"],
  },,
    {
    id: "loop-voice",
    title: "Loop Voice (B2B AI Voice Platform)",
    subtitle: "Enterprise Conversational Voice AI Platform",
    description: "B2B AI voice agent platform targeting insurance, dental, and property management verticals with real-time speech-to-speech workflows.",
    longDescription: "Product specification and architecture concept for Loop Voice, a B2B AI Voice Agent platform. Designed to automate inbound and outbound phone calls for insurance claims, dental appointment scheduling, and property tenant inquiries using WebSockets and real-time LLM voice pipelines.",
    image: OctaVoiceImg,
    link: "#",
    duration: "2025 - Concept",
    role: "AI Product Architect",
    team: "Individual Concept",
    client: "B2B Market Concept",
    associatedWith: "Personal Project",
    technologies: ["Python", "WebSockets", "OpenAI Realtime API", "Twilio Voice", "FastAPI"],
    features: ["Real-Time Bi-Directional Voice Streaming", "Insurance & Dental Appointment Scheduling", "Automated Call Transcript & Summary Generation", "CRM Webhook Integration"],
    challenges: ["Keeping voice latency under 500ms over WebSockets", "Handling background noise and speech interruptions", "Seamless integration with third-party CRM systems"],
    achievements: ["Full product architecture & requirements brief", "Tested real-time voice latency benchmarks", "Market specification across 3 business verticals"],
    tags: ["AI Voice", "WebSockets", "Python", "Concept"],
  },,
    {
    id: "streampulse-pipeline",
    title: "StreamPulse Data Pipeline",
    subtitle: "Real-Time Streaming ETL & Ingestion System",
    description: "High-throughput streaming pipeline ingesting 100k+ events/sec using Apache Kafka, Spark Streaming, and Airflow-orchestrated ETL into a Snowflake data warehouse.",
    longDescription: "StreamPulse is a production-grade real-time data pipeline built for high-volume event ingestion and transformation. Apache Kafka serves as the distributed message broker, Apache Spark Streaming processes and transforms events at scale, and Apache Airflow orchestrates the batch ETL DAGs that load clean data into Snowflake. dbt handles layered data transformations (staging → marts) with full data lineage and automated testing.",
    image: StreamPulseImg,
    link: "#",
    duration: "2025 - Project",
    role: "Data Engineer",
    team: "Individual Project",
    client: "Data Platform",
    associatedWith: "Personal Project",
    technologies: ["Apache Kafka", "Apache Spark", "Apache Airflow", "Snowflake", "Python", "dbt", "AWS S3"],
    features: ["100k+ Events/sec Kafka Topic Ingestion", "Spark Streaming Real-Time Micro-Batch Processing", "Airflow DAG-Based ETL Orchestration", "dbt Layered Data Transformations (Staging to Marts)"],
    challenges: ["Achieving exactly-once semantics across Kafka & Spark", "Managing schema evolution for rapidly changing event payloads", "Monitoring pipeline SLA breaches in real time"],
    achievements: ["Sustained 100k+ events/sec with zero data loss", "End-to-end pipeline latency under 3 seconds", "dbt data tests catching 100% of schema regressions"],
    tags: ["Data Engineering", "Streaming", "ETL", "Kafka"],
  },,
    {
    id: "datavault-warehouse",
    title: "DataVault Cloud Warehouse",
    subtitle: "Scalable Cloud Data Warehouse & Analytics Hub",
    description: "Multi-source cloud data warehouse built on Snowflake with dbt-modeled marts, Airflow-scheduled pipelines, and a self-serve BI layer for business analysts.",
    longDescription: "DataVault is an end-to-end cloud data warehousing solution designed to consolidate data from CRM, ERP, and operational databases into a single source of truth. Data is ingested via Fivetran connectors, modeled using dbt (OBT, star schema, data vault patterns), and orchestrated by Airflow. The presentation layer powers business dashboards and ad-hoc SQL for analysts using Metabase.",
    image: DataVaultImg,
    link: "#",
    duration: "2025 - Project",
    role: "Data Engineer",
    team: "Individual Project",
    client: "Enterprise Analytics",
    associatedWith: "Personal Project",
    technologies: ["Snowflake", "dbt", "Apache Airflow", "Python", "PostgreSQL", "AWS S3", "Metabase"],
    features: ["Multi-Source Data Ingestion (CRM, ERP, APIs)", "dbt Star Schema & Data Vault Modeling", "Automated Data Quality Tests with dbt Tests", "Self-Serve BI Layer via Metabase Dashboards"],
    challenges: ["Resolving slowly changing dimensions across data sources", "Cost optimization for Snowflake warehouse scaling", "Maintaining data freshness SLAs for 15+ source systems"],
    achievements: ["Consolidated 15+ data sources into one warehouse", "Reduced analyst query time from hours to seconds", "99.9% pipeline uptime over 6-month operational period"],
    tags: ["Data Engineering", "Data Warehouse", "Snowflake", "dbt"],
  },,
    {
    id: "featureforge-ml",
    title: "FeatureForge ML Platform",
    subtitle: "Feature Store & ML Experiment Lifecycle Management",
    description: "End-to-end ML platform combining a feature store, experiment tracking via MLflow, automated hyperparameter tuning, and model registry with versioning.",
    longDescription: "FeatureForge is a unified ML platform that eliminates the gap between data science experimentation and production ML engineering. Features a centralized feature store backed by PostgreSQL and Redis for low-latency serving, MLflow for full experiment tracking and artifact logging, Optuna-driven hyperparameter optimization, and a model registry with staged promotion workflows from dev to staging to production.",
    image: FeatureForgeImg,
    link: "#",
    duration: "2025 - Project",
    role: "ML Engineer",
    team: "Individual Project",
    client: "ML Platform",
    associatedWith: "Personal Project",
    technologies: ["Python", "MLflow", "Scikit-learn", "XGBoost", "FastAPI", "PostgreSQL", "Redis"],
    features: ["Centralized Feature Store with Online/Offline Serving", "MLflow Experiment Tracking & Artifact Registry", "Optuna Automated Hyperparameter Optimization", "Staged Model Promotion (Dev to Staging to Production)"],
    challenges: ["Sub-10ms feature serving latency for production models", "Reproducible experiment runs across distributed compute", "Clean feature versioning with backward compatibility"],
    achievements: ["50% reduction in model development cycle time", "100% experiment reproducibility via MLflow artifacts", "Feature serving latency under 8ms at p99"],
    tags: ["ML Engineering", "MLflow", "Feature Store", "Python"],
  },,
    {
    id: "modelserve-hub",
    title: "ModelServe Hub",
    subtitle: "High-Throughput Production ML Model Serving",
    description: "Scalable model serving infrastructure supporting multi-model deployments with A/B testing, ONNX runtime optimization, and Kubernetes auto-scaling.",
    longDescription: "ModelServe Hub is a production-grade ML inference platform enabling teams to deploy, version, and serve multiple models concurrently. Supports ONNX-optimized model formats for CPU/GPU inference, canary A/B test traffic splitting, rolling deployment with zero downtime, and automatic Kubernetes HPA scaling based on request throughput and GPU utilization metrics.",
    image: ModelServeImg,
    link: "#",
    duration: "2025 - Project",
    role: "ML Engineer",
    team: "Individual Project",
    client: "ML Infrastructure",
    associatedWith: "Personal Project",
    technologies: ["Python", "FastAPI", "ONNX Runtime", "Docker", "Kubernetes", "Redis", "Prometheus"],
    features: ["Multi-Model Concurrent Inference Serving", "ONNX Runtime CPU/GPU Optimization", "A/B Canary Traffic Splitting for Model Experiments", "Kubernetes HPA Auto-Scaling on GPU Utilization"],
    challenges: ["Cold-start latency for large transformer-based models", "Concurrent model memory isolation on shared GPU", "Zero-downtime rolling model updates in production"],
    achievements: ["Achieved p95 inference latency under 25ms for ONNX models", "Supported 5,000+ requests/sec on 4-GPU cluster", "Zero downtime across 50+ model version deployments"],
    tags: ["ML Engineering", "Model Serving", "FastAPI", "Production AI"],
  },,
    {
    id: "autotrain-mlops",
    title: "AutoTrain MLOps Platform",
    subtitle: "End-to-End Automated ML Training & Deployment CI/CD",
    description: "MLOps pipeline automating model training triggers, validation gates, experiment logging, and zero-downtime blue-green deployment via GitHub Actions and DVC.",
    longDescription: "AutoTrain is a fully automated MLOps platform bridging data versioning, model training, evaluation, and production deployment. DVC manages dataset and model artifact versioning alongside Git. GitHub Actions triggers training pipelines on data drift detection or code changes, runs automated evaluation gates (AUC, F1 thresholds), and performs blue-green Kubernetes deployments only when quality gates pass.",
    image: AutoTrainImg,
    link: "#",
    duration: "2025 - Open Source",
    role: "MLOps Engineer",
    team: "Individual Project",
    client: "ML CI/CD Platform",
    associatedWith: "Personal Project",
    technologies: ["Python", "MLflow", "DVC", "GitHub Actions", "Docker", "Kubernetes", "Prometheus"],
    features: ["DVC Data & Model Artifact Versioning", "Data Drift Detection Auto-Trigger Pipeline", "Automated Quality Gates (AUC / F1 Thresholds)", "Blue-Green Kubernetes Model Deployment"],
    challenges: ["Reproducible pipeline across different compute environments", "Fast iteration while maintaining audit-grade experiment logs", "Automated rollback on performance regression detection"],
    achievements: ["Cut model release cycle from 2 weeks to 4 hours", "100% automated quality gate enforcement", "Zero production regressions over 30+ automated deployments"],
    tags: ["MLOps", "ML Engineering", "CI/CD", "Automation"],
  },,
    {
    id: "churnshield-analytics",
    title: "ChurnShield Customer Analytics",
    subtitle: "Predictive Customer Churn Modeling & Dashboard",
    description: "XGBoost-powered customer churn prediction system with SHAP explainability, feature engineering pipelines, and an interactive Plotly analytics dashboard.",
    longDescription: "ChurnShield is an end-to-end customer retention analytics solution. Raw transactional and behavioral data is processed through automated Pandas/Scikit-learn feature engineering pipelines. An XGBoost classifier with Optuna-tuned hyperparameters achieves 92% AUC on held-out test data. SHAP values power a business-friendly explainability dashboard built with Plotly Dash, helping customer success teams prioritize high-risk accounts.",
    image: ChurnShieldImg,
    link: "#",
    duration: "2025 - Project",
    role: "Data Scientist",
    team: "Individual Project",
    client: "SaaS Analytics",
    associatedWith: "Personal Project",
    technologies: ["Python", "XGBoost", "Scikit-learn", "Pandas", "NumPy", "Plotly", "SHAP"],
    features: ["Automated Feature Engineering & Selection Pipeline", "XGBoost Churn Classifier (92% AUC)", "SHAP Value Explainability & Feature Importance", "Interactive Plotly Risk Segmentation Dashboard"],
    challenges: ["Severe class imbalance in churn label distribution", "Feature drift detection over time for retraining triggers", "Making SHAP explanations accessible to non-technical stakeholders"],
    achievements: ["92% AUC on hold-out test set with XGBoost", "Identified top 5 churn drivers from 80+ features", "Enabled proactive retention for 1,200+ high-risk accounts"],
    tags: ["Data Science", "Machine Learning", "XGBoost", "Analytics"],
  },,
    {
    id: "finsight-forecaster",
    title: "FinSight Time-Series Forecaster",
    subtitle: "Financial Revenue & Demand Forecasting System",
    description: "Hybrid forecasting system combining Facebook Prophet seasonality decomposition and LSTM deep learning for multi-step financial revenue prediction.",
    longDescription: "FinSight is a production-ready time-series forecasting platform combining classical decomposition (Facebook Prophet) with deep learning (LSTM/Transformer). Prophet handles seasonality, holidays, and trend breaks, while a PyTorch LSTM ensemble captures complex non-linear patterns. The system generates 30/60/90-day revenue forecasts with confidence intervals, visualized on an interactive Plotly dashboard with automatic model retraining on new data arrival.",
    image: FinSightImg,
    link: "#",
    duration: "2025 - Project",
    role: "Data Scientist",
    team: "Individual Project",
    client: "FinTech Analytics",
    associatedWith: "Personal Project",
    technologies: ["Python", "PyTorch", "Prophet", "Pandas", "NumPy", "Plotly", "Scikit-learn"],
    features: ["Hybrid Prophet + LSTM Ensemble Forecasting", "Multi-Horizon 30/60/90-Day Revenue Predictions", "Confidence Interval & Uncertainty Quantification", "Automated Model Retraining on New Data Arrival"],
    challenges: ["Handling irregular seasonality and outlier events", "Ensemble weighting between classical and deep models", "Efficient inference for near-real-time forecast updates"],
    achievements: ["12% MAPE on 30-day revenue forecast horizon", "Outperformed ARIMA baseline by 34% on RMSE", "Automated weekly retraining with zero manual intervention"],
    tags: ["Data Science", "Time Series", "LSTM", "Forecasting"],
  },,
    {
    id: "datalens-dashboard",
    title: "DataLens BI Dashboard",
    subtitle: "Self-Serve Business Intelligence & Analytics Platform",
    description: "React-based self-serve BI platform with drag-and-drop chart builder, SQL-driven data sources, scheduled reports, and role-based workspace access.",
    longDescription: "DataLens is a lightweight, self-hosted BI platform enabling business analysts to explore data and build dashboards without writing code. The backend exposes a Python/FastAPI query layer over PostgreSQL and Snowflake. The React frontend features a drag-and-drop chart builder using Recharts and Plotly, with chart types including time-series, funnel, heatmap, and geo maps. Dashboards support scheduled PDF/email delivery and RBAC workspace sharing.",
    image: DataLensImg,
    link: "#",
    duration: "2024 - Project",
    role: "Full-Stack Data Engineer",
    team: "Individual Project",
    client: "Analytics Platform",
    associatedWith: "Personal Project",
    technologies: ["React", "TypeScript", "FastAPI", "Python", "PostgreSQL", "Plotly", "Pandas"],
    features: ["Drag-and-Drop Chart Builder (Time-Series, Funnel, Geo)", "Live SQL Query Editor with Auto-Complete", "Scheduled PDF Dashboard Email Delivery", "Role-Based Workspace & Dashboard Sharing"],
    challenges: ["Streaming large query result sets without browser freezing", "Maintaining chart render performance for 100k+ row datasets", "Multi-tenant workspace isolation with shared DB connections"],
    achievements: ["Rendered 100k-row datasets in under 800ms", "Used by 50+ analysts with zero performance degradation", "Reduced reporting turnaround from days to minutes"],
    tags: ["BI", "Data Visualization", "Analytics", "Data Science"],
  },,
    {
    id: "loop-hire",
    title: "Loop Hire (AI Recruitment)",
    subtitle: "AI-Powered Talent Matching SaaS Concept",
    description: "AI-powered recruitment SaaS concept targeting Pakistan & Gulf SMEs for automated resume parsing, candidate scoring, and automated interview scheduling.",
    longDescription: "Designed an AI-powered talent acquisition platform targeting SMEs in Pakistan and the Gulf region. Features vector embedding search with pgvector for candidate-job matching, automated PDF resume parsing using OpenAI, and automated candidate shortlisting workflows.",
    image: LoopHireImg,
    link: "#",
    duration: "2025 - Concept",
    role: "SaaS Architect & Founder",
    team: "Individual Concept",
    client: "SME Market Concept",
    associatedWith: "Personal Project",
    technologies: ["Next.js 15", "TypeScript", "OpenAI", "pgvector", "Node.js", "Tailwind CSS"],
    features: ["Automated AI PDF Resume Extraction", "Semantic Candidate Matching via pgvector", "Automated Candidate Shortlist Scoring", "Role-Based Employer Dashboard"],
    challenges: ["Ensuring unbiased candidate scoring algorithms", "Fast vector search across large resume databases", "User-friendly employer management workflow"],
    achievements: ["Complete product architecture specification", "Prototype vector search pipeline", "Market-validated SME recruitment workflow"],
    tags: ["AI", "SaaS", "Recruitment", "Next.js"],
  },,
    {
    id: "payflow-gateway",
    title: "PayFlow Gateway",
    subtitle: "Multi-Currency Payment Orchestration Engine",
    description: "Unified payment abstraction layer routing international credit card transactions, processing webhook retries via BullMQ, and generating receipts.",
    longDescription: "Multi-provider payment gateway engine orchestrating transactions across Stripe and Tap Payments. Handles multi-currency conversion, automated webhook retry queues via BullMQ, invoice generation, and PCI-compliant audit logging.",
    image: PayFlowImg,
    link: "#",
    duration: "2025 - Project",
    role: "Backend Architect",
    team: "Individual Project",
    client: "Fintech Platform",
    associatedWith: "Personal Project",
    technologies: ["Node.js", "Express", "TypeScript", "Stripe API", "Tap Payments", "PostgreSQL", "BullMQ"],
    features: ["Unified Payment Provider Abstraction Layer", "Automated Webhook Retry Queues via BullMQ", "Multi-Currency Auto Conversion & Tax Rules", "PCI-Compliant Audit Log Storage"],
    challenges: ["Ensuring idempotent payment execution across retries", "Handling payment provider API rate limits", "PCI-DSS security compliance verification"],
    achievements: ["100% idempotent transaction processing", "Automated webhook retry resilience", "Sub-150ms payment routing latency"],
    tags: ["Fintech", "Payments", "Stripe", "BullMQ"],
  },,
    {
    id: "graphnexus-api",
    title: "GraphNexus API Gateway",
    subtitle: "Federated GraphQL API Gateway with Microservices",
    description: "Apollo Federation-based GraphQL gateway unifying 6+ downstream microservice schemas, with DataLoader batching, Redis caching, and JWT auth middleware.",
    longDescription: "GraphNexus is an enterprise-grade federated GraphQL API gateway built with Apollo Federation v2 and NestJS. It unifies 6+ independently deployable microservice sub-graphs into a single supergraph. Implements DataLoader for N+1 query elimination, Redis-backed query response caching, persisted query support, and JWT-based auth middleware with field-level authorization directives. Observability via OpenTelemetry tracing to Jaeger.",
    image: TaskPulseImg,
    link: "#",
    duration: "2025 - Project",
    role: "Backend Engineer",
    team: "Individual Project",
    client: "Enterprise API Platform",
    associatedWith: "Personal Project",
    technologies: ["NestJS", "GraphQL", "Apollo Federation", "Redis", "PostgreSQL", "Docker", "TypeScript"],
    features: ["Apollo Federation v2 Federated Supergraph", "DataLoader N+1 Query Elimination", "Redis Query Response Caching Layer", "OpenTelemetry Distributed Tracing to Jaeger"],
    challenges: ["Schema composition conflicts across 6+ sub-graph teams", "Deep query depth limiting without over-restriction", "Accurate distributed tracing across federated resolvers"],
    achievements: ["Reduced client API surface from 6 endpoints to 1", "70% reduction in database round-trips via DataLoader", "End-to-end trace visibility across all sub-graphs"],
    tags: ["Backend", "GraphQL", "NestJS", "API Gateway"],
  },,
    {
    id: "devpulse-telemetry",
    title: "DevPulse Telemetry",
    subtitle: "Real-Time Microservices Health & Log Aggregator",
    description: "High-throughput telemetry platform monitoring microservice uptime, API latency spikes, memory metrics, and live log streaming via Socket.io.",
    longDescription: "Developer telemetry dashboard designed to monitor distributed Node.js microservices. Streams real-time server health metrics, memory usage, CPU load, and error logs using Socket.io and Redis Pub/Sub, visualized through interactive Recharts dashboards.",
    image: DevPulseImg,
    link: "#",
    duration: "2024 - Project",
    role: "Full-Stack Software Engineer",
    team: "Individual Project",
    client: "Developer Tooling",
    associatedWith: "Personal Project",
    technologies: ["Node.js", "Express", "Socket.io", "Redis Pub/Sub", "React", "Recharts", "Docker"],
    features: ["Real-Time Bi-Directional WebSocket Log Streaming", "CPU, RAM & Memory Heap Telemetry Widgets", "Custom Latency Threshold & Spike Alerts", "Docker Container Agent Deployment"],
    challenges: ["Streaming 1,000+ log lines per second without browser lag", "Redis Pub/Sub event synchronization across instances", "Low CPU overhead telemetry daemon design"],
    achievements: ["Handled 5,000+ events/sec with zero packet drops", "Real-time microservice latency visibility", "Lightweight Docker container agent"],
    tags: ["DevOps", "Telemetry", "Socket.io", "Redis"],
  },,
    {
    id: "taskpulse-ai",
    title: "TaskPulse AI Workflow",
    subtitle: "Enterprise Intelligent Project & Task Automation",
    description: "AI-powered project management platform with real-time kanban boards, automated task assignment via LLM scoring, and daily standup summaries.",
    longDescription: "Enterprise task management and workflow automation platform built for engineering teams. Features real-time drag-and-drop Kanban boards using WebSockets, automated task breakdown and effort estimation using OpenAI, sprint progress analytics, and automated daily standup digest generation.",
    image: TaskPulseImg,
    link: "#",
    duration: "2025 - Project",
    role: "Full-Stack Software Engineer",
    team: "Individual Project",
    client: "Agile Teams",
    associatedWith: "Personal Project",
    technologies: ["Next.js 15", "TypeScript", "Tailwind CSS", "Node.js", "Express", "MongoDB", "OpenAI API", "Socket.io"],
    features: ["Real-Time Collaborative Drag-and-Drop Kanban Board", "AI-Powered Sprint Task Effort Estimation & Scoring", "Automated Slack & Email Daily Standup Summaries", "Role-Based Access Control & Workspace Auditing"],
    challenges: ["Bi-directional WebSocket sync for multi-user card drag actions", "LLM prompt tuning for reliable task story point estimations", "Optimizing MongoDB index queries for complex sprint analytics"],
    achievements: ["Sub-50ms card move updates across connected clients", "Automated 80% of daily standup report compilation", "Scalable multi-workspace data isolation model"],
    tags: ["SaaS", "AI", "Agile", "Next.js"],
  },,
    {
    id: "clouddesk-workspace",
    title: "CloudDesk Workspace",
    subtitle: "No-Code Automated Workflow & Form Builder",
    description: "Drag-and-drop workflow automation editor allowing non-technical enterprise users to build custom multi-step forms and approval routing.",
    longDescription: "Drag-and-drop form and workflow builder engineered for enterprise internal operations. Features a visual canvas editor, custom form field validation schemas, automated email trigger dispatches, and role-based approval routing.",
    image: CloudDeskImg,
    link: "#",
    duration: "2024 - Project",
    role: "Full-Stack Developer",
    team: "Individual Project",
    client: "Enterprise Productivity",
    associatedWith: "Personal Project",
    technologies: ["React", "Redux Toolkit", "TypeScript", "Node.js", "MongoDB", "Tailwind CSS"],
    features: ["Visual Drag-and-Drop Form Canvas", "Custom Validation Rule Builder", "Multi-Step Manager Approval Workflows", "Automated Email & Slack Webhook Triggers"],
    challenges: ["Complex nested form state management in React", "Dynamic MongoDB JSON schema compilation", "Smooth canvas drag-and-drop performance"],
    achievements: ["Empowered non-tech staff to build 50+ forms", "Reduced form creation turnaround from days to minutes", "High-performance canvas rendering"],
    tags: ["No-Code", "React", "Workflow", "SaaS"],
  },,
    {
    id: "medicare-portal",
    title: "MediCare Telehealth",
    subtitle: "Telemedicine & Patient Scheduling System",
    description: "Telemedicine portal featuring secure WebRTC video consultations, real-time doctor scheduling, prescription PDF S3 uploads, and SMS alerts.",
    longDescription: "Full-stack telehealth platform connecting patients with certified medical specialists. Includes real-time WebRTC video consultation rooms, doctor slot scheduling, digital prescription generation with AWS S3 storage, and automated SMS appointment reminders.",
    image: MediCareImg,
    link: "#",
    duration: "2024 - Project",
    role: "Full-Stack Developer",
    team: "Individual Project",
    client: "Healthcare System",
    associatedWith: "Personal Project",
    technologies: ["Next.js", "TypeScript", "Node.js", "WebSockets", "WebRTC", "MongoDB", "AWS S3"],
    features: ["Peer-to-Peer WebRTC Video Call Rooms", "Real-Time Doctor Slot Booking Calendar", "Digital Prescription Upload to AWS S3", "Twilio Automated SMS Appointment Reminders"],
    challenges: ["Low-latency WebRTC peer connection handling", "Strict HIPAA data privacy & encryption controls", "Handling doctor scheduling timezone offsets"],
    achievements: ["Sub-200ms WebRTC connection establishment", "Zero video call dropouts during consultations", "HIPAA-compliant document storage on AWS S3"],
    tags: ["Healthcare", "WebRTC", "Next.js", "AWS"],
  },,
    {
    id: "usa-resume-writers",
    title: "USA Resume Writers",
    subtitle: "High-Converting Professional Brand Site",
    description: "Dynamic brand site with live chat integration, lead generation forms, automated email workflows, and 95+ PageSpeed optimization.",
    longDescription: "Created a high-converting, responsive brand site for USA Resume Writers. Built with React, TypeScript, and Framer Motion for smooth micro-animations. Features automated lead generation forms, third-party live chat integration, and automated email notifications, achieving a 95+ Google PageSpeed score.",
    image: USAResumeWritersImg,
    link: "https://www.usaresumewriters.com/",
    duration: "Mar 2025 - Apr 2025",
    role: "Full-Stack Developer",
    team: "1 Member",
    client: "MartechSol",
    associatedWith: "MartechSol",
    technologies: ["React", "TypeScript", "Tailwind CSS", "Framer Motion", "SendGrid"],
    features: ["Automated Lead Generation Forms", "Integrated Live Chat Support", "Fluid Micro-Animations (Framer Motion)", "95+ Google PageSpeed Performance Score"],
    challenges: ["Optimizing complex animations for mobile browsers", "Seamless email dispatch trigger handling", "Cross-browser layout consistency"],
    achievements: ["Significantly boosted customer conversion rates", "95+ Google Web Vitals performance score", "Zero layout shifts across mobile viewports"],
    tags: ["Web", "React", "Branding", "Marketing"],
  },,
    {
    id: "codesprint-cli",
    title: "CodeSprint Developer CLI",
    subtitle: "Developer Productivity & Boilerplate CLI Tool",
    description: "Command-line tool accelerating MERN and Next.js project initialization with pre-configured JWT auth, Tailwind CSS, Docker scripts, and CI/CD.",
    longDescription: "Open-source Node.js command-line utility designed to scaffold production-ready full-stack projects in seconds. Interactively prompts developers for database choices (MongoDB/PostgreSQL), authentication strategies (JWT/OAuth), UI framework setup, and generates ready-to-deploy Docker Compose & GitHub Actions workflows.",
    image: AIDBThumbnail,
    link: "#",
    duration: "2024 - Open Source",
    role: "Tool Author",
    team: "Open Source",
    client: "Developer Community",
    associatedWith: "Open Source",
    technologies: ["Node.js", "TypeScript", "Commander.js", "Inquirer.js", "GitHub Actions", "Docker"],
    features: ["Interactive Terminal Prompt Scaffolding", "Automated JWT Auth & Middleware Setup", "Docker Compose & Nginx Production Configs", "Pre-configured GitHub Actions CI/CD Workflows"],
    challenges: ["Maintaining cross-platform CLI compatibility (Linux, macOS, Windows)", "Fast file template generation without external dependencies", "Automated testing of generated boilerplates"],
    achievements: ["Scaffolds full-stack production repo in under 5 seconds", "500+ CLI downloads on npm", "Zero-config Docker & CI/CD deployment readiness"],
    tags: ["DevTools", "CLI", "TypeScript", "Node.js"],
  },,
];

export const skillsData = [
  {
    category: "Full-Stack & MERN Stack",
    gradient: "from-yellow-400 to-orange-500",
    icon: <SiReact />,
    skills: [
      { name: "Full Stack Engineering", icon: <HiLightningBolt />, color: "text-purple-600 dark:text-purple-400" },
      { name: "MERN Stack Architecture", icon: <HiLightningBolt />, color: "text-teal-600 dark:text-teal-400" },
      { name: "React JS", icon: <SiReact />, color: "text-cyan-600 dark:text-cyan-400" },
      { name: "Node JS", icon: <SiNodedotjs />, color: "text-green-600 dark:text-green-400" },
      { name: "Express JS", icon: <SiExpress />, color: "text-gray-600 dark:text-gray-300" },
      { name: "MongoDB", icon: <SiMongodb />, color: "text-green-600 dark:text-green-400" },
      { name: "TypeScript", icon: <SiTypescript />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Next JS", icon: <SiNextdotjs />, color: "text-gray-900 dark:text-white" },
      { name: "Redux", icon: <SiRedux />, color: "text-purple-600 dark:text-purple-400" },
      { name: "REST & WebSockets", icon: <MdOutlineHttp />, color: "text-purple-600 dark:text-purple-400" },
    ],
  },
  {
    category: "Front-End Engineering",
    gradient: "from-blue-400 to-purple-500",
    icon: <SiReact />,
    skills: [
      { name: "Frontend Engineering", icon: <SiReact />, color: "text-blue-600 dark:text-blue-400" },
      { name: "React JS", icon: <SiReact />, color: "text-cyan-600 dark:text-cyan-400" },
      { name: "Next JS", icon: <SiNextdotjs />, color: "text-gray-900 dark:text-white" },
      { name: "TypeScript", icon: <SiTypescript />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Tailwind CSS", icon: <SiTailwindcss />, color: "text-teal-600 dark:text-teal-400" },
      { name: "Redux Toolkit", icon: <SiRedux />, color: "text-purple-600 dark:text-purple-400" },
      { name: "React Query", icon: <SiReactquery />, color: "text-pink-600 dark:text-pink-400" },
      { name: "Framer Motion", icon: <SiFramer />, color: "text-gray-900 dark:text-white" },
      { name: "Material UI", icon: <SiReact />, color: "text-blue-700 dark:text-blue-500" },
      { name: "Chakra UI", icon: <SiChakraui />, color: "text-teal-600 dark:text-teal-400" },
      { name: "HTML5", icon: <SiHtml5 />, color: "text-orange-600 dark:text-orange-400" },
      { name: "CSS3", icon: <SiCss3 />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Vite", icon: <SiVite />, color: "text-yellow-600 dark:text-yellow-300" },
    ],
  },
  {
    category: "Back-End Engineering",
    gradient: "from-green-400 to-blue-500",
    icon: <SiNodedotjs />,
    skills: [
      { name: "Backend Engineering", icon: <SiNodedotjs />, color: "text-pink-600 dark:text-pink-400" },
      { name: "Node JS", icon: <SiNodedotjs />, color: "text-green-600 dark:text-green-400" },
      { name: "Express JS", icon: <SiExpress />, color: "text-gray-600 dark:text-gray-300" },
      { name: "NestJS", icon: <SiNestjs />, color: "text-red-700 dark:text-red-500" },
      { name: "FastAPI", icon: <SiFastapi />, color: "text-teal-600 dark:text-teal-400" },
      { name: "Django", icon: <SiDjango />, color: "text-emerald-800 dark:text-emerald-400" },
      { name: "REST APIs", icon: <MdOutlineHttp />, color: "text-purple-600 dark:text-purple-400" },
      { name: "GraphQL", icon: <SiGraphql />, color: "text-pink-700 dark:text-pink-500" },
      { name: "Apollo Federation", icon: <SiApollographql />, color: "text-indigo-600 dark:text-indigo-300" },
      { name: "Socket.io", icon: <SiSocketdotio />, color: "text-gray-900 dark:text-white" },
      { name: "Redis", icon: <SiRedis />, color: "text-red-600 dark:text-red-400" },
      { name: "Kafka", icon: <SiApachekafka />, color: "text-gray-700 dark:text-gray-200" },
      { name: "Nginx", icon: <SiNginx />, color: "text-green-700 dark:text-green-500" },
    ],
  },
  {
    category: "Data Engineering",
    gradient: "from-orange-400 to-red-500",
    icon: <HiDatabase />,
    skills: [
      { name: "Apache Spark", icon: <SiApachespark />, color: "text-orange-600 dark:text-orange-400" },
      { name: "Apache Airflow", icon: <SiApacheairflow />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Apache Kafka", icon: <SiApachekafka />, color: "text-gray-700 dark:text-gray-300" },
      { name: "Snowflake", icon: <SiSnowflake />, color: "text-sky-600 dark:text-sky-300" },
      { name: "dbt", icon: <SiDbt />, color: "text-orange-700 dark:text-orange-500" },
      { name: "Pandas", icon: <SiPandas />, color: "text-blue-700 dark:text-blue-500" },
      { name: "NumPy", icon: <SiNumpy />, color: "text-blue-500 dark:text-blue-300" },
      { name: "BigQuery", icon: <SiGooglecloud />, color: "text-blue-500 dark:text-blue-300" },
      { name: "ETL Pipelines", icon: <HiLightningBolt />, color: "text-amber-600 dark:text-amber-400" },
      { name: "AWS Glue", icon: <HiChip />, color: "text-orange-600 dark:text-orange-400" },
      { name: "Delta Lake", icon: <HiDatabase />, color: "text-blue-600 dark:text-blue-400" },
    ],
  },
  {
    category: "Machine Learning & MLOps",
    gradient: "from-purple-400 to-indigo-600",
    icon: <HiChip />,
    skills: [
      { name: "PyTorch", icon: <SiPytorch />, color: "text-red-700 dark:text-red-500" },
      { name: "TensorFlow", icon: <SiTensorflow />, color: "text-orange-600 dark:text-orange-400" },
      { name: "Scikit-learn", icon: <SiScikitlearn />, color: "text-orange-600 dark:text-orange-300" },
      { name: "MLflow", icon: <SiMlflow />, color: "text-blue-600 dark:text-blue-400" },
      { name: "XGBoost", icon: <HiChip />, color: "text-green-700 dark:text-green-500" },
      { name: "ONNX Runtime", icon: <HiChip />, color: "text-gray-700 dark:text-gray-300" },
      { name: "Feature Store", icon: <HiDatabase />, color: "text-indigo-600 dark:text-indigo-400" },
      { name: "Model Serving", icon: <HiLightningBolt />, color: "text-pink-600 dark:text-pink-400" },
      { name: "DVC", icon: <SiGit />, color: "text-purple-600 dark:text-purple-400" },
    ],
  },
  {
    category: "AI Engineering & LLMs",
    gradient: "from-pink-400 to-red-500",
    icon: <HiSparkles />,
    skills: [
      { name: "LangChain", icon: <SiLangchain />, color: "text-green-600 dark:text-green-300" },
      { name: "LangGraph", icon: <SiLangchain />, color: "text-green-700 dark:text-green-400" },
      { name: "OpenAI API", icon: <SiOpenai />, color: "text-green-600 dark:text-green-300" },
      { name: "Gemini API", icon: <SiGooglecloud />, color: "text-blue-500 dark:text-blue-300" },
      { name: "Hugging Face", icon: <SiHuggingface />, color: "text-yellow-600 dark:text-yellow-300" },
      { name: "RAG Pipelines", icon: <HiSparkles />, color: "text-purple-600 dark:text-purple-400" },
      { name: "pgvector", icon: <HiDatabase />, color: "text-indigo-600 dark:text-indigo-400" },
      { name: "Multi-Agent Systems", icon: <GiTeamIdea />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Transformer Fine-Tuning", icon: <SiTensorflow />, color: "text-orange-600 dark:text-orange-400" },
    ],
  },
  {
    category: "Data Science & Analytics",
    gradient: "from-teal-400 to-blue-500",
    icon: <HiChartBar />,
    skills: [
      { name: "Plotly", icon: <SiPlotly />, color: "text-purple-600 dark:text-purple-400" },
      { name: "Matplotlib", icon: <HiChartBar />, color: "text-blue-600 dark:text-blue-400" },
      { name: "SHAP Explainability", icon: <HiSparkles />, color: "text-amber-600 dark:text-amber-400" },
      { name: "Prophet Forecasting", icon: <HiChartBar />, color: "text-blue-500 dark:text-blue-300" },
      { name: "Predictive Analytics", icon: <HiChip />, color: "text-green-600 dark:text-green-400" },
      { name: "Metabase BI", icon: <HiDatabase />, color: "text-blue-600 dark:text-blue-400" },
    ],
  },
  {
    category: "Databases & Storage",
    gradient: "from-purple-400 to-pink-500",
    icon: <SiMongodb />,
    skills: [
      { name: "MongoDB", icon: <SiMongodb />, color: "text-green-600 dark:text-green-400" },
      { name: "PostgreSQL", icon: <SiPostgresql />, color: "text-blue-500 dark:text-blue-300" },
      { name: "MySQL", icon: <SiMysql />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Redis", icon: <SiRedis />, color: "text-red-600 dark:text-red-400" },
      { name: "Snowflake DB", icon: <SiSnowflake />, color: "text-sky-600 dark:text-sky-400" },
      { name: "pgvector", icon: <HiDatabase />, color: "text-indigo-600 dark:text-indigo-400" },
      { name: "Supabase", icon: <SiSupabase />, color: "text-green-600 dark:text-green-400" },
      { name: "Firebase", icon: <SiFirebase />, color: "text-yellow-600 dark:text-yellow-400" },
      { name: "SQLite", icon: <SiSqlite />, color: "text-blue-800 dark:text-blue-200" },
      { name: "Prisma ORM", icon: <SiPrisma />, color: "text-purple-600 dark:text-purple-400" },
    ],
  },
  {
    category: "DevOps & Cloud",
    gradient: "from-cyan-400 to-blue-600",
    icon: <SiGit />,
    skills: [
      { name: "Docker", icon: <SiDocker />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Kubernetes", icon: <SiKubernetes />, color: "text-blue-700 dark:text-blue-500" },
      { name: "GitHub Actions", icon: <SiGithubactions />, color: "text-blue-500 dark:text-blue-300" },
      { name: "Google Cloud", icon: <SiGooglecloud />, color: "text-red-600 dark:text-red-400" },
      { name: "Microsoft Azure", icon: <VscAzure />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Git", icon: <SiGit />, color: "text-orange-600 dark:text-orange-400" },
      { name: "Terraform", icon: <SiTerraform />, color: "text-purple-700 dark:text-purple-500" },
      { name: "Cloudflare", icon: <SiCloudflare />, color: "text-orange-600 dark:text-orange-300" },
    ],
  },
  {
    category: "Programming Languages",
    gradient: "from-yellow-400 to-orange-500",
    icon: <HiLightningBolt />,
    skills: [
      { name: "Python", icon: <SiPython />, color: "text-blue-500 dark:text-blue-300" },
      { name: "TypeScript", icon: <SiTypescript />, color: "text-blue-600 dark:text-blue-400" },
      { name: "JavaScript", icon: <SiJavascript />, color: "text-yellow-600 dark:text-yellow-400" },
      { name: "SQL", icon: <HiDatabase />, color: "text-sky-600 dark:text-sky-400" },
      { name: "Java", icon: <FaJava />, color: "text-red-600 dark:text-red-400" },
      { name: "C++", icon: <SiCplusplus />, color: "text-purple-600 dark:text-purple-400" },
      { name: "C-Sharp", icon: <TbBrandCSharp />, color: "text-purple-700 dark:text-purple-500" },
      { name: "Solidity", icon: <SiSolidity />, color: "text-gray-600 dark:text-gray-400" },
    ],
  },
  {
    category: "Testing & Practices",
    gradient: "from-indigo-400 to-purple-600",
    icon: <GiTeamIdea />,
    skills: [
      { name: "Agile Methodologies", icon: <GiTeamIdea />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Jest", icon: <SiJest />, color: "text-red-600 dark:text-red-300" },
      { name: "Vitest", icon: <SiJest />, color: "text-yellow-600 dark:text-yellow-400" },
      { name: "Cypress", icon: <SiCypress />, color: "text-green-600 dark:text-green-300" },
      { name: "Software Testing", icon: <GiTestTubes />, color: "text-green-600 dark:text-green-400" },
      { name: "System Design", icon: <HiLightningBolt />, color: "text-amber-600 dark:text-amber-400" },
    ],
  },
  {
    category: "Dev Tools & IDEs",
    gradient: "from-blue-500 to-cyan-400",
    icon: <VscCode />,
    skills: [
      { name: "Cursor AI", icon: <HiSparkles />, color: "text-purple-600 dark:text-purple-400" },
      { name: "GitHub Copilot", icon: <SiGithubcopilot />, color: "text-sky-600 dark:text-sky-400" },
      { name: "VS Code", icon: <VscVscode />, color: "text-blue-700 dark:text-blue-500" },
      { name: "Jupyter Notebook", icon: <SiJupyter />, color: "text-orange-700 dark:text-orange-500" },
      { name: "PyCharm", icon: <SiPycharm />, color: "text-green-600 dark:text-green-400" },
      { name: "Google Colab", icon: <SiGooglecolab />, color: "text-orange-600 dark:text-orange-400" },
      { name: "Antigravity", icon: <FaSpaceShuttle />, color: "text-orange-700 dark:text-orange-500" },
    ],
  },
];

export const experienceData = [
  {
    company: "Alvi Global Enterprises (AGE)",
    shortCompany: "AGE",
    logo: AGELogo,
    logoBg: "bg-meelo-cardLavender",
    iconBg: "bg-white",
    position: "Senior Software Engineer",
    duration: "September 2025 – Present",
    totalDuration: "Present",
    location: "Karachi, Pakistan",
    responsibilities: [
      "Led end-to-end development of Startup Ninja, a MERN-based multi-tenant B2B SaaS platform on 8+ microservices; engineered CRM lead-management, document-generation, and AI Chat & Image pipelines using OpenAI APIs.",
      "Containerized services with Docker; leveraged Redis Pub/Sub and BullMQ for distributed background jobs, Stripe billing sync, and asynchronous task orchestration.",
      "Secured APIs with JWT rotation, token blacklisting, CSRF protection, and bcrypt hashing; integrated RAG pipelines using LangChain and pgvector for document-aware AI features.",
    ],
    projects: ["Startup Ninja B2B SaaS", "CRM Lead Management", "Document Generator", "AI Chat Pipeline"],
    technologies: ["MERN Stack", "TypeScript", "Microservices", "Docker", "Redis", "BullMQ", "Stripe", "OpenAI", "LangChain"],
  },
  {
    company: "eSanad (Contract)",
    shortCompany: "eSanad",
    logo: EsanadLogo,
    logoBg: "bg-meelo-cardMint",
    iconBg: "bg-white",
    position: "Software Engineer",
    duration: "April 2025 – September 2025",
    totalDuration: "6 mos",
    location: "Remote (UAE)",
    responsibilities: [
      "Designed and delivered features on a MERN-stack insurance CRM, building organization/employee management and motor/travel insurance modules integrated with third-party APIs (Adamjee, Watania, Insurance House).",
      "Integrated the Tap Payments gateway and automated policy issuance via payment-status validation, significantly reducing manual policy-processing time.",
      "Optimized MongoDB aggregation pipelines and indexing strategies, improving average API response times and overall throughput by over 40%.",
    ],
    projects: ["eSanad Insurance CRM", "eSanad Corporate Website", "Tap Payment Integration"],
    technologies: ["React", "Node.js", "TypeScript", "MongoDB", "Tap Payments", "Adamjee API", "Insurance House API"],
  },
  {
    company: "MartechSol",
    shortCompany: "MTS",
    logo: MartechsolLogo,
    logoBg: "bg-meelo-cardPink",
    iconBg: "bg-[#0b1f3a]",
    position: "Software Engineer",
    duration: "October 2024 – April 2025",
    totalDuration: "7 mos",
    location: "Karachi, Pakistan",
    responsibilities: [
      "Built a full-featured HRM system and CRM from scratch on the MERN stack covering Attendance, Payroll, Finance, RBAC, and Ticketing modules.",
      "Developed responsive interfaces with React, Redux Toolkit, TypeScript, and Tailwind CSS; designed RESTful and WebSocket APIs for real-time notifications.",
      "Implemented CI/CD pipelines with GitHub Actions that cut deployment time by 60% and improved MongoDB query response times through compound indexing and aggregation optimization.",
    ],
    projects: ["Enterprise HRM Portal", "Enterprise CRM", "USA Resume Writers"],
    technologies: ["MERN Stack", "React", "Redux", "TypeScript", "Tailwind CSS", "Node.js", "CI/CD"],
  },
  {
    company: "CharCentric",
    shortCompany: "CC",
    logo: CharcentricLogo,
    logoBg: "bg-meelo-cardBlue",
    iconBg: "bg-[#1e293b]",
    position: "Software Engineer",
    duration: "August 2023 – August 2024",
    totalDuration: "1 yr 1 mo",
    location: "Remote (UAE, Abu Dhabi)",
    responsibilities: [
      "Contributed to RMG LMS (React, Node.js, MongoDB, AWS S3): built a complex quizzing system, automated certificate issuance, and integrated S3 presigned URL media streaming.",
      "Built full-stack financial analytics dashboards for APCO Worldwide (200+ hospitals): engineered ETL data pipelines converting unstructured financial documents into structured KPIs surfaced through Recharts dashboards.",
      "Maintained legacy backend systems, resolving critical performance bottlenecks via query analysis and indexing strategies that improved critical API endpoints by up to 5x.",
    ],
    projects: ["RMG LMS Platform", "GPAnalytix / APCO Dashboard", "AI Finance Tracker"],
    technologies: ["React", "Node.js", "MongoDB", "AWS S3", "ETL Pipelines", "TypeScript", "Recharts"],
  },
];

export const educationData = [
  {
    degree: "M.S. Computer Science (Gold Medalist 🥇)",
    shortDegree: "MSCS",
    institution: "Mohammad Ali Jinnah University (MAJU)",
    gpa: "CGPA 3.97 / 4.00 • Gold Medalist",
    status: "Graduated • Gold Medalist",
    duration: "September 2024 – July 2026",
    location: "Karachi, Pakistan",
    accentBg: "bg-meelo-cardLavender",
    description: "Awarded Gold Medal in M.S. Computer Science for highest academic achievement. Recipient of 100% Merit Scholarship (Full Tuition Waiver) awarded for maintaining a perfect 4.00 / 4.00 GPA across each semester. Master's Thesis on AI-driven translation and summarization of Pakistani Supreme Court judgments into Urdu and Sindhi using fine-tuned transformer models (NLLB-200, mBART-50, mT5), achieving 88.9% Term Success Rate for Urdu and 84.7% for Sindhi. Poster presented at IEEE HTC 2026.",
    highlights: [
      "Awarded Gold Medal in M.S. Computer Science for highest academic achievement",
      "Awarded 100% Merit Scholarship (Full Tuition Waiver) for maintaining a 4.00 / 4.00 GPA in each semester",
      "Specialized in Software Systems, Applied Machine Learning & NLP (CGPA 3.97 / 4.00)",
      "Thesis: AI-driven legal judgment translation & summarization into Urdu and Sindhi using fine-tuned transformer models (NLLB-200, mBART-50, mT5)",
      "Achieved 88.9% Term Success Rate (TSR) for Urdu and 84.7% for Sindhi",
      "Poster presented at IEEE HTC 2026 (Supervised by Dr. Shaukat Wasi)",
    ],
    tags: ["Gold Medalist 🥇", "100% Merit Scholarship", "4.00/4.00 Semester GPA", "Software Systems", "Applied ML", "NLP", "IEEE HTC 2026"],
  },
  {
    degree: "B.S. Computer Science",
    shortDegree: "BSCS",
    institution: "Sukkur IBA University",
    gpa: "CGPA 3.11 / 4.00 • Distinction",
    status: "Graduated with Distinction",
    duration: "August 2019 – September 2023",
    location: "Sukkur, Pakistan",
    accentBg: "bg-meelo-cardMint",
    description: "Focused on software engineering, data structures, and algorithms. Completed a capstone project on intelligent systems recognized for innovation.",
    highlights: [
      "Focused on core software engineering, data structures, and algorithms",
      "Completed a capstone project on intelligent systems recognized for innovation",
      "Graduated with Distinction and strong academic standing",
    ],
    tags: ["Software Engineering", "Data Structures", "Algorithms", "Intelligent Systems", "Distinction"],
  },
];

export const certificationsData = [
  {
    title: "Mastering Big Data Analytics",
    issuer: "Great Learning",
    date: "Dec 2025",
    credentialId: "HRABPYXS",
    credentialUrl: "https://www.mygreatlearning.com/verify/HRABPYXS",
    description: "Comprehensive certification on big data processing architectures, data warehousing, ETL pipelines, and scalable data analytics.",
    skills: ["Big Data", "Data Analytics", "ETL", "SQL", "Data Pipeline", "Python"],
    featured: true,
  },
  {
    title: "Gemini API by Google",
    issuer: "Udacity",
    date: "Jul 2024",
    credentialId: "549c0b28-45af-11ef-a35e-9b9a02ba6f0f",
    credentialUrl: "https://www.udacity.com/certificate/e/549c0b28-45af-11ef-a35e-9b9a02ba6f0f",
    description: "Verified certificate of completion for the Gemini API by Google course. Covered prompt engineering, safety, function calling, and building AI features with Google AI Studio.",
    skills: ["Gemini API", "Google AI Studio", "Prompt Engineering", "AI/ML", "REST APIs", "Node.js", "Python"],
    featured: true,
  },
  {
    title: "Learning Full-Stack JavaScript Development: MongoDB, Node, and React",
    issuer: "LinkedIn Learning",
    date: "Jul 2023",
    credentialUrl: "https://www.linkedin.com/learning/certificates/52b8fc7c980d16a2f92667217053cbdf9d334baecaba83f1fd400132dbfc3704",
    description: "Comprehensive course on full-stack JavaScript development using MongoDB, Node.js, Express, and React.js.",
    skills: ["Full-Stack JavaScript", "React.js", "Node.js", "MongoDB", "Express.js", "REST APIs"],
    featured: true,
  },
  {
    title: "Node.js Backend Basics with Best Practices",
    issuer: "Coursera",
    date: "Feb 2023",
    credentialId: "BF44X7AFBV4R",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/BF44X7AFBV4R",
    description: "Learned Node.js backend fundamentals, middleware design, security practices, and scalable server-side architecture.",
    skills: ["Node.js", "Express", "REST APIs", "Backend Development", "Security"],
    featured: true,
  },
  {
    title: "Introduction to Front-end Development with ReactJS",
    issuer: "Coursera",
    date: "Feb 2023",
    credentialId: "USAW78LSYV5C",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/USAW78LSYV5C",
    description: "Modern React.js fundamentals, component lifecycle, hooks, state management, and responsive UI design.",
    skills: ["React.js", "JavaScript", "HTML5", "CSS3", "Frontend Development"],
    featured: true,
  },
  {
    title: "TypeScript in React: Get Started",
    issuer: "Coursera",
    date: "Feb 2023",
    credentialId: "6T4NNEAA28EW",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/6T4NNEAA28EW",
    description: "Building type-safe React applications using TypeScript interfaces, generics, props typing, and event handling.",
    skills: ["TypeScript", "React.js", "Type Safety", "JSX", "Frontend"],
    featured: true,
  },
  {
    title: "Introduction to MongoDB",
    issuer: "MongoDB University",
    date: "Jun 2023",
    credentialId: "MDB5j5kr5ffez",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description: "Foundational knowledge of MongoDB, NoSQL document modeling, indexing, and Atlas setup.",
    skills: ["MongoDB", "NoSQL", "Database Design", "Atlas Cloud"],
    featured: false,
  },
  {
    title: "MongoDB Aggregation",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDBtrupbrqmyf",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description: "Mastered the MongoDB aggregation framework for complex data transformations, analytics pipelines, and reporting.",
    skills: ["MongoDB", "Aggregation Framework", "Data Pipelines", "Analytics"],
    featured: false,
  },
  {
    title: "MongoDB Atlas Search",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDBz2so80wyug",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description: "Implemented full-text search capabilities, fuzzy search, and relevance ranking using MongoDB Atlas Search.",
    skills: ["MongoDB", "Atlas Search", "Full-Text Search", "NoSQL"],
    featured: false,
  },
  {
    title: "Connecting to a MongoDB Database",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDB6rcj7kqx6f",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description: "Learned effective strategies for connection pooling, driver optimization, and secure authentication in MongoDB.",
    skills: ["MongoDB", "Driver Connectivity", "Security"],
    featured: false,
  },
  {
    title: "React (Basic)",
    issuer: "HackerRank",
    date: "Mar 2023",
    credentialId: "2832fd9d6c55",
    credentialUrl: "https://www.hackerrank.com/certificates/2832fd9d6c55",
    description: "Verified skill assessment for React.js components, state management, props, and event handling.",
    skills: ["React.js", "JavaScript", "Frontend Development"],
    featured: false,
  },
  {
    title: "Angular (Basic)",
    issuer: "HackerRank",
    date: "Mar 2023",
    credentialId: "ce9a1fbb806f",
    credentialUrl: "https://www.hackerrank.com/certificates/ce9a1fbb806f",
    description: "Verified skill assessment for Angular framework fundamentals, components, and directives.",
    skills: ["Angular", "TypeScript", "Web Development"],
    featured: false,
  },
  {
    title: "Learning Git and GitHub",
    issuer: "LinkedIn Learning",
    date: "Sep 2023",
    credentialUrl: "https://www.linkedin.com/learning/certificates/864e388fc77539a9e499d8889689e734e51560a4f6612928c1a6701484df6b2d",
    description: "Covered Git fundamentals, branching strategies, rebase, merge conflict resolution, and GitHub collaboration workflows.",
    skills: ["Git", "GitHub", "Version Control", "CI/CD Workflows"],
    featured: false,
  },
  {
    title: "Build a Twitter Clone Front-End with ReactJS",
    issuer: "Coursera",
    date: "Jul 2023",
    credentialId: "THVJDLKCAVH6",
    credentialUrl: "https://www.coursera.org/account/accomplishments/certificate/THVJDLKCAVH6",
    description: "Built a full Twitter-like frontend using ReactJS, SASS, and REST APIs, focusing on responsive UI design.",
    skills: ["React.js", "SASS", "HTML5", "CSS3", "REST APIs"],
    featured: false,
  },
];

export const articlesData = [
  {
    title: "Building Scalable React Applications with Next.js 14",
    excerpt: "Explore the latest features in Next.js 14 and learn how to build high-performance, scalable React applications with server components and improved routing.",
    publishDate: "2024-01-15",
    readTime: "8 min read",
    category: "Web Development",
    tags: ["React", "Next.js", "Performance", "Server Components"],
    url: "#",
    author: "Amjad Ali",
    slug: "building-scalable-react-applications-nextjs-14",
  },
  {
    title: "Mastering TypeScript: Advanced Patterns and Best Practices",
    excerpt: "Deep dive into advanced TypeScript patterns, generic constraints, and architectural patterns that will make your code more maintainable and type-safe.",
    publishDate: "2023-12-20",
    readTime: "12 min read",
    category: "Programming",
    tags: ["TypeScript", "JavaScript", "Best Practices", "Architecture"],
    url: "#",
    author: "Amjad Ali",
    slug: "mastering-typescript-advanced-patterns",
  },
  {
    title: "Cloud Architecture: Designing for Scale with AWS",
    excerpt: "Learn how to design and implement scalable cloud architectures using AWS services, with focus on reliability, security, and cost optimization.",
    publishDate: "2023-11-10",
    readTime: "15 min read",
    category: "Cloud Computing",
    tags: ["AWS", "Cloud Architecture", "Scalability", "DevOps"],
    url: "#",
    author: "Amjad Ali",
    slug: "cloud-architecture-aws-scale",
  },
  {
    title: "The Future of Web Development: AI Integration and Automation",
    excerpt: "Exploring how artificial intelligence is reshaping web development workflows, from code generation to automated testing and deployment.",
    publishDate: "2023-10-25",
    readTime: "10 min read",
    category: "Technology Trends",
    tags: ["AI", "Machine Learning", "Automation", "Future Tech"],
    url: "#",
    author: "Amjad Ali",
    slug: "future-web-development-ai-integration",
  },
  {
    title: "Database Design Patterns for Modern Applications",
    excerpt: "Comprehensive guide to database design patterns, covering relational and NoSQL databases, with practical examples and performance considerations.",
    publishDate: "2023-09-15",
    readTime: "14 min read",
    category: "Database",
    tags: ["Database Design", "SQL", "NoSQL", "Performance"],
    url: "#",
    author: "Amjad Ali",
    slug: "database-design-patterns-modern-applications",
  },
];

export const testimonialsData = [
  {
    name: "Sarah Johnson",
    position: "CTO",
    company: "TechStart Inc.",
    rating: 5,
    testimonial: "Amjad delivered an exceptional full-stack solution that exceeded our expectations. His attention to detail and ability to translate complex requirements into elegant code is remarkable.",
    projectType: "E-commerce Platform",
  },
  {
    name: "Michael Chen",
    position: "Lead Developer",
    company: "Digital Solutions Ltd.",
    rating: 5,
    testimonial: "Working with Amjad was a game-changer for our team. His expertise in React and Node.js helped us modernize our legacy system. He's not just a great developer but also an excellent mentor.",
    projectType: "System Modernization",
  },
  {
    name: "Emily Rodriguez",
    position: "Product Manager",
    company: "InnovateCorp",
    rating: 5,
    testimonial: "Amjad's ability to understand our business requirements and translate them into technical solutions is outstanding. The mobile-responsive dashboard he built significantly improved our productivity.",
    projectType: "Analytics Dashboard",
  },
  {
    name: "David Thompson",
    position: "Founder & CEO",
    company: "StartupHub",
    rating: 5,
    testimonial: "From concept to deployment, Amjad managed our entire web application project flawlessly. His expertise in cloud architecture and modern development practices helped us scale efficiently.",
    projectType: "SaaS Platform",
  },
];
