import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiCplusplus,
  SiSolidity,
  SiReact,
  SiNextdotjs,
  SiHtml5,
  SiCss3,
  SiTailwindcss,
  SiChakraui,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiMysql,
  SiPostgresql,
  SiFirebase,
  SiTensorflow,
  SiKeras,
  SiScikitlearn,
  SiOpencv,
  SiPytorch,
  SiOpenai,
  SiGit,
  SiDocker,
  SiKubernetes,
  SiGooglecloud,
  SiSupabase,
  SiPrisma,
  SiJenkins,
  SiGithubcopilot,
  SiNestjs,
  SiGraphql,
  SiApollographql,
  SiSocketdotio,
  SiRedux,
  SiReactquery,
  SiFramer,
  SiVite,
  SiStorybook,
  SiReacthookform,
  SiHuggingface,
  SiGithubactions,
  SiVercel,
  SiNetlify,
  SiTerraform,
  SiCloudflare,
  SiRedis,
  SiNginx,
  SiApachekafka,
  SiSqlite,
  SiJest,
  SiCypress,
  SiTestinglibrary,
  SiAndroidstudio,
  SiEclipseide,
  SiApache,
  SiJupyter,
  SiGooglecolab,
  SiIntellijidea,
  SiPycharm,
  SiWebstorm,
  SiSublimetext,
} from "react-icons/si";
import { MdOutlineHttp, MdDevices } from "react-icons/md";
import { GiTeamIdea, GiTestTubes } from "react-icons/gi";
import { TbBrandCSharp } from "react-icons/tb";
import { VscAzure, VscCode, VscVscode } from "react-icons/vsc";
import { FaJava, FaSpaceShuttle } from "react-icons/fa";
import { HiLightningBolt, HiSparkles, HiChip } from "react-icons/hi";

// Images
import CRMThumbnail from "@/app/assets/CRM Thumbnail.png";
import HRMThumbnail from "@/app/assets/HRM Thumbnail.png";
import AIDBThumbnail from "@/app/assets/AIDashboard.png";
import EaseWebThumbnail from "@/app/assets/EaseWen Thumbnail.png";

export const projects = [
  {
    id: "startup-ninja",
    title: "Startup Ninja",
    subtitle: "AI-Powered SaaS Ecosystem",
    description:
      "A unified ecosystem combining AI Chat, Image Gen, Social Media Studio, and No-Code Website Builder.",
    longDescription:
      "Startup Ninja is a robust, AI-driven SaaS platform designed to centralize digital creativity and management. It features a versatile AI Chat Assistant and Image Generator for content creation. The Social Media Studio allows for automated post scheduling across Facebook, Instagram, X, and LinkedIn using OAuth 2.0. The platform also includes a No-Code Website Builder powered by GrapesJS, enabling users to create responsive websites effortlessly.",
    image: AIDBThumbnail,
    link: "https://startupninja.netlify.app/",
    duration: "Sep 2024 - Ongoing",
    role: "Full-Stack Developer",
    team: "2 Members",
    // client: "Alvi Global Enterprises (AGE)",
    // associatedWith: "Alvi Global Enterprises (AGE)",
    technologies: [
      "MERN Stack",
      "TypeScript",
      "Microservices",
      "AWS",
      "OpenAI",
      "Google Gemini",
      "GrapesJS",
    ],
    features: [
      "AI Chat & Image Generation",
      "Multi-platform Social Media Scheduling",
      "Drag-and-Drop Website Builder",
      "OAuth 2.0 Integration",
      "Tiered Subscription System",
    ],
    challenges: [
      "Orchestrating multiple AI services reliably",
      "Complex social media API compliance",
      "State management for no-code editor",
    ],
    achievements: [
      "Unified 4 major tools in one platform",
      "Seamless social media automation",
      "Scalable microservices architecture",
    ],
    tags: ["SaaS", "AI", "MERN", "Automation"],
  },
  {
    id: "crm-esanad",
    title: "CRM (eSanad)",
    subtitle: "Enterprise CRM & Insurance Module",
    description:
      "Enhanced CRM with organization management and third-party motor insurance API integrations.",
    longDescription:
      "Contributed to the evolution of the eSanad CRM by introducing modules for organization and employee management. A significant part of the role involved developing a motor insurance module that integrates with third-party APIs from providers like Adamjee and Insurance House, facilitating seamless policy issuance and management within the CRM.",
    image: CRMThumbnail,
    link: "https://admin.esanad.com/",
    duration: "Apr 2025 - Aug 2025",
    role: "Full-Stack Developer",
    team: "6+ Members",
    client: "eSanad",
    associatedWith: "eSanad",
    technologies: [
      "Next.js",
      "Node.js",
      "JavaScript",
      "Third-Party Billing APIs",
    ],
    features: [
      "Organization & Employee Management",
      "Motor and Travel Insurance Issuance",
      "Third-party API Integration (Adamjee, Insurance House)",
      "Automated Billing Workflows",
    ],
    challenges: [
      "Standardizing data from diverse insurance APIs",
      "Ensuring real-time synchronization",
      "Legacy code refactoring",
    ],
    achievements: [
      "Streamlined insurance policy workflows",
      "Enhanced system modularity",
      "Reduced manual data entry errors",
    ],
    tags: ["CRM", "Fintech", "Integration", "Next.js"],
  },
  {
    id: "esanad-website",
    title: "eSanad Website",
    subtitle: "Travel Insurance Portal",
    description:
      "Core travel insurance features with payment gateway integration for automated policy issuance.",
    longDescription:
      "Developed the core travel insurance functionality for the eSanad public website. This included integrating APIs from insurance providers such as Watania and Insurance House. Additionally, automated the payment and policy issuance process by securely integrating the Tap Payment gateway, ensuring a smooth user experience from quote to policy generation.",
    image: EaseWebThumbnail,
    link: "https://www.esanad.com/",
    duration: "Apr 2025 - Aug 2025",
    role: "Full-Stack Developer",
    team: "6+ Members",
    client: "eSanad",
    associatedWith: "eSanad",
    technologies: ["Next.js", "Node.js", "JavaScript", "Tap Payment Gateway"],
    features: [
      "Real-time Travel Insurance Quotes",
      "Secure Payment Processing (Tap)",
      "Instant Policy Generation",
      "Provider API Integration (Watania, etc.)",
    ],
    challenges: [
      "Secure handling of payment transactions",
      "Handling API downtime gracefully",
      "Responsive insurance quote forms",
    ],
    achievements: [
      "Fully automated insurance purchase flow",
      "Improved conversion rates",
      "Secure payment compliance",
    ],
    tags: ["E-commerce", "Insurance", "Web", "Next.js"],
  },
  {
    id: "crm-martechsol",
    title: "CRM MartechSol",
    subtitle: "Unified Business Management Platform",
    description:
      "Comprehensive CRM for sales tracking, contact management, and support with advanced analytics.",
    longDescription:
      "Built a powerful CRM system to centralize customer relationship management. It tracks sales leads, manages contacts, and handles support requests. The system features advanced analytics to provide insights into sales performance. The UI was built with React and TypeScript based on Figma designs, while the Node.js backend ensures secure data handling. Deployed with CI/CD pipelines.",
    image: CRMThumbnail,
    link: "https://crm.martechsol.com/",
    duration: "Jan 2025 - Apr 2025",
    role: "Full-Stack Developer",
    team: "1 Member",
    client: "Martechsol",
    associatedWith: "Martechsol",
    technologies: ["MERN Stack", "TypeScript", "DevOps", "Figma"],
    features: [
      "Lead & Opportunity Tracking",
      "Customer Support Ticketing",
      "Sales Performance Analytics",
      "Role-Based Dashboards",
    ],
    challenges: [
      "Complex data modeling for sales pipelines",
      "Implementing real-time dashboard updates",
      "Figma to Code fidelity",
    ],
    achievements: [
      "Delivered end-to-end CRM solution",
      "Automated deployment workflows",
      "High-performance responsive UI",
    ],
    tags: ["CRM", "MERN", "Analytics", "DevOps"],
  },
  {
    id: "hrm-martechsol",
    title: "HRM Portal",
    subtitle: "Human Resource Management System",
    description:
      "Feature-rich HRM for attendance, payroll, and team management with role-based access.",
    longDescription:
      "Developed a complete HRM system to automate core HR operations. Modules include Biometric Attendance tracking, Payroll processing, Leave management, and Team organization. The system enforces Role-Based Access Control (RBAC) for security. Frontend built with React/TypeScript from Figma, backend with Node.js, and deployed via DevOps best practices.",
    image: HRMThumbnail,
    link: "https://portal.martechsol.com/",
    duration: "Oct 2024 - Jan 2025",
    role: "Full-Stack Developer",
    team: "1 Member",
    client: "Martechsol",
    associatedWith: "Martechsol",
    technologies: ["MERN Stack", "TypeScript", "RBAC", "DevOps"],
    features: [
      "Automated Payroll & Finance",
      "Biometric Attendance Sync",
      "Leave & Approval Workflows",
      "Role-Based Access Control",
    ],
    challenges: [
      "Complex payroll calculation logic",
      "Secure implementation of RBAC",
      "Handling large employee datasets",
    ],
    achievements: [
      "Automated 90% of manual HR tasks",
      "Zero payroll calculation errors",
      "Scalable architecture implementation",
    ],
    tags: ["HRM", "Enterprise", "MERN", "Automation"],
  },
  {
    id: "usa-resume-writers",
    title: "USA Resume Writers",
    subtitle: "Professional Brand Website",
    description:
      "Dynamic brand site with live chat, email automation, and lead generation workflows.",
    longDescription:
      "Created a professional, high-performance brand website for USA Resume Writers. The site includes lead generation forms, integrated live chat for customer support, and automated email workflows. Built using React, TypeScript, and Framer Motion for premium animations, ensuring high engagement and conversion rates.",
    image: EaseWebThumbnail,
    link: "https://www.usaresumewriters.com/",
    duration: "Mar 2025 - Apr 2025",
    role: "Full-Stack Developer",
    team: "1 Member",
    client: "Martechsol",
    associatedWith: "Martechsol",
    technologies: ["MERN Stack", "TypeScript", "Framer Motion", "Email Automation"],
    features: [
      "Live Chat Integration",
      "Automated Lead Gen Workflows",
      "Premium Animations (Framer Motion)",
      "SEO Optimized Architecture",
    ],
    challenges: [
      "Balancing high-end animations with performance",
      "Seamless 3rd-party chat integration",
      "Optimizing for high SEO scores",
    ],
    achievements: [
      "Significantly increased online leads",
      "Achieved 95+ Performance Score",
      "Smooth, premium user experience",
    ],
    tags: ["Brand", "Web", "Animation", "Marketing"],
  },
  {
    id: "smart-ai-dashboard",
    title: "Smart AI Dashboard",
    subtitle: "AI-Powered Analytics Platform",
    description:
      "High-performance AI dashboard for APCO Worldwide, bridging frontend and backend for data insights.",
    longDescription:
      "Contributed to a flagship AI application for APCO Worldwide (via SnowHeap). As a Full Stack Engineer, bridged the gap between complex backend AI models and the frontend UI. The dashboard provides intelligent, data-driven insights through interactive visualizations, ensuring a seamless user experience for complex data sets.",
    image: AIDBThumbnail,
    link: "#",
    duration: "Jan 2024 - Aug 2024",
    role: "Full-Stack Software Engineer",
    team: "6+ Members",
    client: "SnowHeap / APCO Worldwide",
    associatedWith: "CharCentric",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS", "Figma", "AI/ML"],
    features: [
      "Interactive Data Visualization",
      "Real-time AI Inference Display",
      "Complex State Management",
      "Responsive Analytical Widgets",
    ],
    challenges: [
      "Visualizing heavy AI datasets performantly",
      "Synchronizing frontend with async AI processes",
      "Strict enterprise security compliance",
    ],
    achievements: [
      "Delivered enterprise-grade analytics tool",
      "Optimized large-scale data rendering",
      "Successful cross-functional collaboration",
    ],
    tags: ["AI", "Analytics", "Dashboard", "Enterprise"],
  },
  {
    id: "finance-tracker",
    title: "AI Finance Tracker",
    subtitle: "Intelligent Personal Finance Assistant",
    description:
      "Mobile-first finance app with OpenAI-powered insights and real-time spending alerts.",
    longDescription:
      "Developed a mobile-centric personal finance application. It leverages a fine-tuned OpenAI assistant to provide personalized financial advice and budgeting tips. The app tracks income/expenses and visualizes financial health through interactive charts, offering real-time alerts for budget limits.",
    image: AIDBThumbnail,
    link: "#",
    duration: "Feb 2024 - Jun 2024",
    role: "Full-Stack Developer",
    team: "1 Member",
    client: "CharCentric",
    associatedWith: "CharCentric",
    technologies: ["Next.js", "TypeScript", "OpenAI API", "Tailwind CSS"],
    features: [
      "AI Financial Advisor (OpenAI)",
      "Expense Visualization",
      "Real-time Budget Alerts",
      "Mobile-First Experience",
    ],
    challenges: [
      "Fine-tuning LLM for financial accuracy",
      "Creating responsive charts for mobile",
      "Real-time data persistence",
    ],
    achievements: [
      "Effective personalized financial guidance",
      "Intuitive mobile-first interface",
      "Seamless AI integration",
    ],
    tags: ["Fintech", "AI", "Mobile", "Personal Finance"],
  },
  {
    id: "rmg-lms",
    title: "RMG LMS",
    subtitle: "Enterprise Learning Management System",
    description:
      "LMS with complex quizzing, AWS S3 media handling, and automated certification.",
    longDescription:
      "Participated in building a comprehensive Learning Management System. Key contributions included developing a complex quizzing engine, integrating AWS S3 for secure video/image rendering, and implementing automated certificate issuance logic. Also worked on dynamic theme management and full course progress tracking.",
    image: HRMThumbnail,
    link: "#",
    duration: "Aug 2023 - Nov 2023",
    role: "Full-Stack Developer",
    team: "3+ Members",
    client: "CharCentric",
    associatedWith: "CharCentric",
    technologies: ["Next.js", "TypeScript", "AWS S3", ".NET Backend"],
    features: [
      "Advanced Quizzing System",
      "Secure Media Streaming (AWS S3)",
      "Automated Certificate Generation",
      "Course Progress Tracking",
    ],
    challenges: [
      "Securely delivering restricted course content",
      "Complex quiz scoring and state",
      "Integration with .NET backend",
    ],
    achievements: [
      "Robust enterprise learning platform",
      "Seamless media experience",
      "Reliable certification workflow",
    ],
    tags: ["EdTech", "LMS", "AWS", "Enterprise"],
  },
  {
    id: "easeweb",
    title: "EaseWeb",
    subtitle: "No-Code Website Builder",
    description:
      "Drag-and-drop website builder with customizable templates and AWS hosting.",
    longDescription:
      "Built 'EaseWeb', a platform empowering users to create professional websites via a drag-and-drop interface. It features a library of customizable templates and automatically handles hosting via AWS. Designed for small businesses and individuals to build their online presence without coding.",
    image: EaseWebThumbnail,
    link: "#",
    duration: "Aug 2022 - Apr 2023",
    role: "Full-Stack Developer",
    team: "3 Members",
    client: "Sukkur IBA",
    associatedWith: "Sukkur IBA",
    technologies: ["MERN Stack", "Redux", "AWS", "REST APIs"],
    features: [
      "Drag-and-Drop Page Editor",
      "Customizable Templates",
      "Live Site Preview",
      "Automated Deployment",
    ],
    challenges: [
      "Building a performant visual editor",
      "Generating clean code from visual blocks",
      "Managing user deployments on AWS",
    ],
    achievements: [
      "Enabled non-tech users to build sites",
      "Robust template system",
      "Scalable cloud architecture",
    ],
    tags: ["No-Code", "Web Builder", "MERN", "SaaS"],
  },
];

export const skillsData = [
  {
    category: "Programming Languages",
    gradient: "from-yellow-400 to-orange-500",
    icon: <HiLightningBolt />,
    skills: [
      { name: "JavaScript", icon: <SiJavascript />, color: "text-yellow-600 dark:text-yellow-400" },
      { name: "TypeScript", icon: <SiTypescript />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Python", icon: <SiPython />, color: "text-blue-500 dark:text-blue-300" },
      { name: "Java", icon: <FaJava />, color: "text-red-600 dark:text-red-400" },
      { name: "C++", icon: <SiCplusplus />, color: "text-purple-600 dark:text-purple-400" },
      { name: "C-Sharp", icon: <TbBrandCSharp />, color: "text-purple-700 dark:text-purple-500" },
      { name: "Solidity", icon: <SiSolidity />, color: "text-gray-600 dark:text-gray-400" },
    ],
  },
  {
    category: "Front-End",
    gradient: "from-blue-400 to-purple-500",
    icon: <SiReact />,
    skills: [
      { name: "React JS", icon: <SiReact />, color: "text-cyan-600 dark:text-cyan-400" },
      { name: "Next JS", icon: <SiNextdotjs />, color: "text-gray-900 dark:text-white" },
      { name: "HTML", icon: <SiHtml5 />, color: "text-orange-600 dark:text-orange-400" },
      { name: "CSS", icon: <SiCss3 />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Tailwind CSS", icon: <SiTailwindcss />, color: "text-teal-600 dark:text-teal-400" },
      { name: "Material UI", icon: <SiReact />, color: "text-blue-700 dark:text-blue-500" },
      { name: "Chakra UI", icon: <SiChakraui />, color: "text-teal-600 dark:text-teal-400" },
      { name: "Redux", icon: <SiRedux />, color: "text-purple-600 dark:text-purple-400" },
      { name: "React Query", icon: <SiReactquery />, color: "text-pink-600 dark:text-pink-400" },
      { name: "Framer Motion", icon: <SiFramer />, color: "text-gray-900 dark:text-white" },
      { name: "Vite", icon: <SiVite />, color: "text-yellow-600 dark:text-yellow-300" },
      { name: "Storybook", icon: <SiStorybook />, color: "text-pink-700 dark:text-pink-500" },
      {
        name: "React Hook Form",
        icon: <SiReacthookform />,
        color: "text-rose-600 dark:text-rose-400",
      },
    ],
  },
  {
    category: "Back-End",
    gradient: "from-green-400 to-blue-500",
    icon: <SiNodedotjs />,
    skills: [
      { name: "Node JS", icon: <SiNodedotjs />, color: "text-green-600 dark:text-green-400" },
      { name: "Express JS", icon: <SiExpress />, color: "text-gray-600 dark:text-gray-300" },
      { name: "REST APIs", icon: <MdOutlineHttp />, color: "text-purple-600 dark:text-purple-400" },
      { name: "NestJS", icon: <SiNestjs />, color: "text-red-700 dark:text-red-500" },
      { name: "GraphQL", icon: <SiGraphql />, color: "text-pink-700 dark:text-pink-500" },
      { name: "Apollo", icon: <SiApollographql />, color: "text-indigo-600 dark:text-indigo-300" },
      { name: "Socket.io", icon: <SiSocketdotio />, color: "text-gray-900 dark:text-white" },
      { name: "Redis", icon: <SiRedis />, color: "text-red-600 dark:text-red-400" },
      { name: "Kafka", icon: <SiApachekafka />, color: "text-gray-700 dark:text-gray-200" },
      { name: "Nginx", icon: <SiNginx />, color: "text-green-700 dark:text-green-500" },
    ],
  },
  {
    category: "Databases",
    gradient: "from-purple-400 to-pink-500",
    icon: <SiMongodb />,
    skills: [
      { name: "MongoDB", icon: <SiMongodb />, color: "text-green-600 dark:text-green-400" },
      { name: "MySQL", icon: <SiMysql />, color: "text-blue-600 dark:text-blue-400" },
      { name: "PostgreSQL", icon: <SiPostgresql />, color: "text-blue-500 dark:text-blue-300" },
      { name: "Firebase", icon: <SiFirebase />, color: "text-yellow-600 dark:text-yellow-400" },
      { name: "SQLite", icon: <SiSqlite />, color: "text-blue-800 dark:text-blue-200" },
      { name: "Prisma ORM", icon: <SiPrisma />, color: "text-purple-600 dark:text-purple-400" },
    ],
  },
  {
    category: "AI/ML Tools",
    gradient: "from-pink-400 to-red-500",
    icon: <SiTensorflow />,
    skills: [
      { name: "TensorFlow", icon: <SiTensorflow />, color: "text-orange-600 dark:text-orange-400" },
      { name: "Keras", icon: <SiKeras />, color: "text-red-600 dark:text-red-400" },
      {
        name: "Scikit-learn",
        icon: <SiScikitlearn />,
        color: "text-orange-600 dark:text-orange-300",
      },
      { name: "OpenCV", icon: <SiOpencv />, color: "text-green-600 dark:text-green-400" },
      { name: "PyTorch", icon: <SiPytorch />, color: "text-red-700 dark:text-red-500" },
      { name: "ChatGPT", icon: <SiOpenai />, color: "text-green-600 dark:text-green-300" },
      {
        name: "GitHub Copilot",
        icon: <SiGithubcopilot />,
        color: "text-sky-600 dark:text-sky-400",
      },
      {
        name: "Hugging Face",
        icon: <SiHuggingface />,
        color: "text-yellow-600 dark:text-yellow-300",
      },
    ],
  },
  {
    category: "Tools/Platforms",
    gradient: "from-cyan-400 to-blue-600",
    icon: <SiGit />,
    skills: [
      { name: "Git", icon: <SiGit />, color: "text-orange-600 dark:text-orange-400" },
      {
        name: "GitHub Actions",
        icon: <SiGithubactions />,
        color: "text-blue-500 dark:text-blue-300",
      },
      { name: "Docker", icon: <SiDocker />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Kubernetes", icon: <SiKubernetes />, color: "text-blue-700 dark:text-blue-500" },
      { name: "Google Cloud", icon: <SiGooglecloud />, color: "text-red-600 dark:text-red-400" },
      { name: "Microsoft Azure", icon: <VscAzure />, color: "text-blue-600 dark:text-blue-400" },
      { name: "Supabase", icon: <SiSupabase />, color: "text-green-600 dark:text-green-400" },
      { name: "Prisma", icon: <SiPrisma />, color: "text-purple-600 dark:text-purple-400" },
      { name: "Vercel", icon: <SiVercel />, color: "text-gray-900 dark:text-white" },
      { name: "Netlify", icon: <SiNetlify />, color: "text-green-600 dark:text-green-300" },
      { name: "Terraform", icon: <SiTerraform />, color: "text-purple-700 dark:text-purple-500" },
      { name: "Cloudflare", icon: <SiCloudflare />, color: "text-orange-600 dark:text-orange-300" },
    ],
  },
  {
    category: "Dev IDEs",
    gradient: "from-blue-500 to-cyan-400",
    icon: <VscCode />,
    skills: [
      { name: "VS Code", icon: <VscVscode />, color: "text-blue-700 dark:text-blue-500" },
      { name: "Cursor AI", icon: <HiSparkles />, color: "text-purple-600 dark:text-purple-400" },
      {
        name: "Antigravity",
        icon: <FaSpaceShuttle />,
        color: "text-orange-700 dark:text-orange-500",
      },
      {
        name: "Android Studio",
        icon: <SiAndroidstudio />,
        color: "text-green-700 dark:text-green-500",
      },
      { name: "Eclipse", icon: <SiEclipseide />, color: "text-indigo-800 dark:text-indigo-600" },
      { name: "NetBeans", icon: <SiApache />, color: "text-blue-800 dark:text-blue-600" },
      {
        name: "Jupyter Notebook",
        icon: <SiJupyter />,
        color: "text-orange-700 dark:text-orange-500",
      },
      {
        name: "Google Colab",
        icon: <SiGooglecolab />,
        color: "text-orange-600 dark:text-orange-400",
      },
      { name: "Notebook LLM", icon: <HiChip />, color: "text-blue-600 dark:text-blue-400" },
      {
        name: "IntelliJ IDEA",
        icon: <SiIntellijidea />,
        color: "text-pink-700 dark:text-pink-500",
      },
      { name: "PyCharm", icon: <SiPycharm />, color: "text-green-600 dark:text-green-400" },
      { name: "WebStorm", icon: <SiWebstorm />, color: "text-blue-600 dark:text-blue-400" },
      {
        name: "Sublime Text",
        icon: <SiSublimetext />,
        color: "text-orange-700 dark:text-orange-500",
      },
    ],
  },
  {
    category: "Others",
    gradient: "from-indigo-400 to-purple-600",
    icon: <GiTeamIdea />,
    skills: [
      {
        name: "Agile Methodologies",
        icon: <GiTeamIdea />,
        color: "text-blue-600 dark:text-blue-400",
      },
      { name: "CI/CD Pipelines", icon: <SiJenkins />, color: "text-red-600 dark:text-red-400" },
      {
        name: "Responsive Design",
        icon: <MdDevices />,
        color: "text-purple-600 dark:text-purple-400",
      },
      {
        name: "Software Testing",
        icon: <GiTestTubes />,
        color: "text-green-600 dark:text-green-400",
      },
      { name: "Jest", icon: <SiJest />, color: "text-red-600 dark:text-red-300" },
      { name: "Cypress", icon: <SiCypress />, color: "text-green-600 dark:text-green-300" },
      {
        name: "Testing Library",
        icon: <SiTestinglibrary />,
        color: "text-orange-600 dark:text-orange-300",
      },
    ],
  },
];

export const experienceData = [
  {
    company: "Alavi Global Enterprises (AGE)",
    position: "Software Engineer",
    duration: "Sep 2025 - Present",
    location: "Onsite (Pakistan)",
    responsibilities: [
      "Architecting full-stack applications using modern web technologies and frameworks",
      "Implementing robust backend services and RESTful APIs for seamless data integration",
      "Optimizing application performance and ensuring code quality through best practices",
      "Contributing to technical decision-making and mentoring team members",
    ],
    projects: [
      "Enterprise Resource Planning System",
      "Customer Portal Platform",
      "Internal Analytics Dashboard",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "Node.js",
      "TypeScript",
      "REST APIs",
      "Full-Stack Development",
      "System Architecture",
      "Agile",
    ],
  },
  {
    company: "Esanad",
    position: "Software Engineer",
    duration: "Apr 2025 - Sep 2025",
    location: "Remote (UAE)",
    responsibilities: [
      "Delivered production-ready features using test-driven development",
      "Integrated APIs, third-party services, and insurance data platforms",
      "Improved lead automation, digital claims management, and underwriting tools",
      "Ensured code quality, security, and scalability across all development tasks",
    ],
    projects: [
      "Lead Automation System",
      "Digital Claims Management Portal",
      "Insurance Underwriting Platform",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "Node.js",
      "TypeScript",
      "APIs",
      "TDD",
      "Performance Optimization",
      "Security",
    ],
  },
  {
    company: "MarTechSol",
    position: "Software Engineer",
    duration: "Oct 2024 - Apr 2025",
    location: "Karachi, Pakistan",
    responsibilities: [
      "Built and maintained scalable web applications using MERN, Next.js, and WordPress",
      "Designed and integrated RESTful APIs for efficient frontend-backend communication",
      "Implemented CI/CD pipelines and worked with cloud platforms like AWS and Azure",
      "Mentored junior developers and contributed to AI-powered application development",
    ],
    projects: [
      "CRM Management System",
      "HRM Platform",
      "AI-Powered Analytics Dashboard",
    ],
    technologies: [
      "MERN",
      "Next.js",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "WordPress",
      "AWS",
      "Azure",
      "CI/CD",
    ],
  },
  {
    company: "CharCentric",
    position: "Software Engineer",
    duration: "Aug 2023 - Aug 2024",
    location: "Remote (UAE, Abu Dhabi)",
    responsibilities: [
      "Collaborated with cross-functional teams to analyze requirements and align on goals",
      "Designed, developed, and optimized software solutions for performance",
      "Maintained and enhanced existing systems by resolving issues and improvements",
      "Created technical documentation to support streamlined development",
    ],
    projects: [
      "RMG Learning Management System",
      "AI Intelligence Dashboard",
      "Data Analytics Platform",
    ],
    technologies: [
      "React.js",
      "Next.js",
      "Node.js",
      "TypeScript",
      "System Integration",
      "Performance Optimization",
      "AI Dashboards",
      "LMS",
    ],
  },
];

export const educationData = [
  {
    degree: "Master of Science in Computer Science (MSCS)",
    institution: "Mohammad Ali Jinnah University",
    duration: "September 2024 - Present",
    location: "Karachi, Pakistan",
    highlights: [
      "Specializing in advanced software engineering, machine learning, and AI",
      "Conducting research on innovative AI applications and scalable architectures",
      "Focus on cutting-edge technologies and modern development methodologies",
    ],
    achievements: [
      "Advanced Software Engineering",
      "Machine Learning and AI",
      "Research on Innovative AI Applications",
      "Scalable System Architectures",
    ],
    projects: [
      "AI-Powered Analytics Platform",
      "Distributed System Architecture",
      "Machine Learning Research",
    ],
  },
  {
    degree: "Bachelor of Science in Computer Science (BSCS)",
    institution: "Sukkur IBA University",
    duration: "August 2019 - September 2023",
    location: "Sukkur, Pakistan",
    highlights: [
      "Graduated with distinction and strong academic performance",
      "Completed capstone project on intelligent systems with innovation recognition",
      "Built strong foundation in computer science fundamentals and applications",
    ],
    achievements: [
      "Graduated with Distinction",
      "AI, ML, and Data Structures Focus",
      "Capstone Project on Intelligent Systems",
      "Innovation and Performance Recognition",
    ],
    projects: [
      "Intelligent Systems Capstone",
      "Data Structures Optimization",
      "AI/ML Research Project",
    ],
  },
];

export const certificationsData = [
  {
    title: "Gemini API by Google",
    issuer: "Udacity",
    date: "Jul 2024",
    credentialId: "549c0b28-45af-11ef-a35e-9b9a02ba6f0f",
    credentialUrl:
      "https://www.udacity.com/certificate/e/549c0b28-45af-11ef-a35e-9b9a02ba6f0f",
    description:
      "Verified certificate of completion for the Gemini API by Google course. Covered prompt engineering, safety, function calling, and building AI features with Google AI Studio.",
    skills: [
      "Gemini API",
      "Google AI Studio",
      "Prompt Engineering",
      "AI/ML",
      "REST APIs",
      "Node.js",
      "Python",
    ],
  },
  {
    title: "Learning Git and GitHub (2021)",
    issuer: "LinkedIn Learning",
    date: "Sep 2023",
    credentialUrl:
      "https://www.linkedin.com/learning/certificates/864e388fc77539a9e499d8889689e734e51560a4f6612928c1a6701484df6b2d?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_certifications_details%3BRoXx99UhTPypBEXw4r8k0Q%3D%3D",
    description:
      "Covered Git fundamentals, branching, merging, commits, and using GitHub for collaboration and pull requests.",
    skills: [
      "Git",
      "GitHub",
      "Version Control",
      "Branching",
      "Merging",
      "Pull Requests",
    ],
  },
  {
    title: "Build a Twitter Clone Front-End with ReactJS",
    issuer: "Coursera",
    date: "Jul 2023",
    credentialId: "THVJDLKCAVH6",
    credentialUrl:
      "https://www.coursera.org/account/accomplishments/certificate/THVJDLKCAVH6",
    description:
      "Built a Twitter-like front-end using ReactJS, SASS, and REST APIs, focusing on responsive design and modern web technologies.",
    skills: [
      "GitHub",
      "SASS",
      "AWS",
      "CSS",
      "Version Control",
      "Git",
      "HTML5",
      "REST APIs",
      "Web Technologies",
    ],
  },
  {
    title:
      "Learning Full-Stack JavaScript Development: MongoDB, Node, and React",
    issuer: "LinkedIn",
    date: "Jul 2023",
    credentialUrl:
      "https://www.linkedin.com/learning/certificates/52b8fc7c980d16a2f92667217053cbdf9d334baecaba83f1fd400132dbfc3704?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_certifications_details%3BRoXx99UhTPypBEXw4r8k0Q%3D%3D",
    description:
      "Comprehensive course on full-stack JavaScript development using MongoDB, Node.js, and React.",
    skills: [
      "GitHub",
      "SASS",
      "AWS",
      "JavaScript",
      "CSS",
      "Full-Stack Development",
      "MongoDB",
      "Version Control",
      "Git",
      "HTML5",
      "React.js",
      "Node.js",
      "REST APIs",
      "Web Technologies",
    ],
  },
  {
    title: "Connecting to a MongoDB Database",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDB6rcj7kqx6f",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Learned effective strategies for connecting to and interacting with MongoDB databases.",
    skills: ["GitHub", "REST APIs", "Web Technologies"],
  },
  {
    title: "Introduction to MongoDB",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDB5j5kr5ffez",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description: "Foundational knowledge of MongoDB, including key concepts and Atlas setup.",
    skills: ["REST APIs", "Web Technologies"],
  },
  {
    title: "MongoDB Aggregation",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDBtrupbrqmyf",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Mastered the aggregation framework for data analysis and transformation.",
    skills: ["REST APIs", "Web Technologies"],
  },
  {
    title: "MongoDB Atlas Search",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDBz2so80wyug",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Implemented full-text search capabilities using MongoDB Atlas Search.",
    skills: ["MongoDB", "REST APIs", "Search"],
  },
  {
    title: "MongoDB CRUD Operations: Insert and Find",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDB8rqivqxcac",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Essential CRUD operations focusing on inserting and querying documents.",
    skills: ["MongoDB", "Back-End Web Development", "Web Technologies"],
  },
  {
    title: "MongoDB CRUD Operations: Modifying Results",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDBo4ewagduro",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Advanced query techniques to modify and format result sets.",
    skills: ["MongoDB", "Web Technologies"],
  },
  {
    title: "MongoDB CRUD Operations: Replace and Delete",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDB9hosetb4xm",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Managing data lifecycle through replacement and deletion operations.",
    skills: ["MongoDB", "REST APIs", "Web Technologies"],
  },
  {
    title: "MongoDB Data Modeling Intro",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDB4p2hokswb2",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Introduction to schema design and data modeling best practices in MongoDB.",
    skills: ["MongoDB", "REST APIs", "Data Modeling"],
  },
  {
    title: "MongoDB Indexes",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDB9z2b0qt9uf",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Optimizing database performance and query speed using indexes.",
    skills: ["MongoDB", "REST APIs", "Performance"],
  },
  {
    title: "MongoDB Transactions",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDBzu0tam4cc9",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Implementing ACID transactions in MongoDB for data integrity.",
    skills: ["MongoDB", "REST APIs", "Transactions"],
  },
  {
    title: "MongoDB and the Document Model",
    issuer: "MongoDB",
    date: "Jun 2023",
    credentialId: "MDBd8dd9ozggr",
    credentialUrl: "https://learn.mongodb.com/c/EiH32iCGThihgkvrbFyoTw",
    description:
      "Deep dive into the flexibility and power of the document model.",
    skills: ["REST APIs", "Web Technologies"],
  },
  {
    title: "Angular (Basic)",
    issuer: "HackerRank",
    date: "Mar 2023",
    credentialId: "ce9a1fbb806f",
    credentialUrl: "https://www.hackerrank.com/certificates/ce9a1fbb806f",
    description:
      "Demonstrated foundational knowledge of Angular and modern web development.",
    skills: [
      "GitHub",
      "AWS",
      "Git",
      "AngularJS",
      "REST APIs",
      "Web Technologies",
    ],
  },
  {
    title: "React (Basic)",
    issuer: "HackerRank",
    date: "Mar 2023",
    credentialId: "2832fd9d6c55",
    credentialUrl: "https://www.hackerrank.com/certificates/2832fd9d6c55",
    description:
      "Demonstrated foundational knowledge of React.js and component-based development.",
    skills: [
      "GitHub",
      "AWS",
      "Git",
      "HTML5",
      "React.js",
      "REST APIs",
      "Web Technologies",
    ],
  },
  {
    title: "Node.js Backend Basics with Best Practices",
    issuer: "Coursera",
    date: "Feb 2023",
    credentialId: "BF44X7AFBV4R",
    credentialUrl:
      "https://www.coursera.org/account/accomplishments/certificate/BF44X7AFBV4R",
    description:
      "Learned Node.js backend fundamentals and best practices for scalable server-side development.",
    skills: [
      "GitHub",
      "SASS",
      "AWS",
      "CSS",
      "Version Control",
      "Git",
      "HTML5",
      "Node.js",
      "REST APIs",
      "Web Technologies",
    ],
  },
];

export const articlesData = [
  {
    title: "Building Scalable React Applications with Next.js 14",
    excerpt:
      "Explore the latest features in Next.js 14 and learn how to build high-performance, scalable React applications with server components and improved routing.",
    publishDate: "2024-01-15",
    readTime: "8 min read",
    category: "Web Development",
    tags: ["React", "Next.js", "Performance", "Server Components"],
    url: "#",
    author: "Amjad Ali",
    slug: "building-scalable-react-applications-nextjs-14",
  },
  {
    title: "Mastering TypeScript: Advanced Patterns and Best Practices",
    excerpt:
      "Deep dive into advanced TypeScript patterns, generic constraints, and architectural patterns that will make your code more maintainable and type-safe.",
    publishDate: "2023-12-20",
    readTime: "12 min read",
    category: "Programming",
    tags: ["TypeScript", "JavaScript", "Best Practices", "Architecture"],
    url: "#",
    author: "Amjad Ali",
    slug: "mastering-typescript-advanced-patterns",
  },
  {
    title: "Cloud Architecture: Designing for Scale with AWS",
    excerpt:
      "Learn how to design and implement scalable cloud architectures using AWS services, with focus on reliability, security, and cost optimization.",
    publishDate: "2023-11-10",
    readTime: "15 min read",
    category: "Cloud Computing",
    tags: ["AWS", "Cloud Architecture", "Scalability", "DevOps"],
    url: "#",
    author: "Amjad Ali",
    slug: "cloud-architecture-aws-scale",
  },
  {
    title: "The Future of Web Development: AI Integration and Automation",
    excerpt:
      "Exploring how artificial intelligence is reshaping web development workflows, from code generation to automated testing and deployment.",
    publishDate: "2023-10-25",
    readTime: "10 min read",
    category: "Technology Trends",
    tags: ["AI", "Machine Learning", "Automation", "Future Tech"],
    url: "#",
    author: "Amjad Ali",
    slug: "future-web-development-ai-integration",
  },
  {
    title: "Database Design Patterns for Modern Applications",
    excerpt:
      "Comprehensive guide to database design patterns, covering relational and NoSQL databases, with practical examples and performance considerations.",
    publishDate: "2023-09-15",
    readTime: "14 min read",
    category: "Database",
    tags: ["Database Design", "SQL", "NoSQL", "Performance"],
    url: "#",
    author: "Amjad Ali",
    slug: "database-design-patterns-modern-applications",
  },
];

export const testimonialsData = [
  {
    name: "Sarah Johnson",
    position: "CTO",
    company: "TechStart Inc.",
    rating: 5,
    testimonial:
      "Amjad delivered an exceptional full-stack solution that exceeded our expectations. His attention to detail and ability to translate complex requirements into elegant code is remarkable.",
    projectType: "E-commerce Platform",
  },
  {
    name: "Michael Chen",
    position: "Lead Developer",
    company: "Digital Solutions Ltd.",
    rating: 5,
    testimonial:
      "Working with Amjad was a game-changer for our team. His expertise in React and Node.js helped us modernize our legacy system. He's not just a great developer but also an excellent mentor.",
    projectType: "System Modernization",
  },
  {
    name: "Emily Rodriguez",
    position: "Product Manager",
    company: "InnovateCorp",
    rating: 5,
    testimonial:
      "Amjad's ability to understand our business requirements and translate them into technical solutions is outstanding. The mobile-responsive dashboard he built significantly improved our productivity.",
    projectType: "Analytics Dashboard",
  },
  {
    name: "David Thompson",
    position: "Founder & CEO",
    company: "StartupHub",
    rating: 5,
    testimonial:
      "From concept to deployment, Amjad managed our entire web application project flawlessly. His expertise in cloud architecture and modern development practices helped us scale efficiently.",
    projectType: "SaaS Platform",
  },
];
